<div class="box box-info">
    <div class="box-header">
      <h3 class="box-title">Добавить новый</h3>
    </div>
    <div class="box-body">

<?php
$form = $this->form;
$form->prepare();
// Assuming the "contact/process" route exists...
//$form->setAttribute('action', $this->url('csn-cms/default', array('controller' => 'comment', 'action' => 'add'), true)); //'contact/process'));
// or
// $form->setAttribute('action', $this->url('grace-drops/default', array('controller' => 'translation', 'action' => 'add', 'id' => $this->id))); //'contact/process'));

// Set the method attribute for the form
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
//echo $this->formCollection($form);

foreach ( $form as $element ) :
echo '<div class="form-group">'.$this->formRow($element).'</div>';
endforeach;

echo $this->form()->closeTag(); ?>

    </div>
    <!-- /.box-body -->
</div>