<?php
$myRoute = $this->getHelperPluginManager()->getServiceLocator()->get('application')->getMvcEvent()->getRouteMatch()->getMatchedRouteName();
  if ($this->is_xmlhttprequest == 0) {
    echo '<div class="box box-info">
    <div class="box-header">
      <h3 class="box-title">Добавить новый</h3>
    </div>
    <div class="box-body">';
  }else{
    echo '<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
      <div class="progress progress-xxs active" style="display: none;">
        <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
          <span class="sr-only">100% Complete (warning)</span>
        </div>
      </div>';
  }
?>


<?php
$form = $this->form;
$form->prepare();
// Assuming the "contact/process" route exists...
//$form->setAttribute('action', $this->url('csn-cms/default', array('controller' => 'comment', 'action' => 'add'), true)); //'contact/process'));
// or
// $form->setAttribute('action', $this->url('grace-drops/default', array('controller' => 'translation', 'action' => 'add', 'id' => $this->id))); //'contact/process'));

// Set the method attribute for the form
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
//echo $this->formCollection($form);

foreach ( $form as $element ) :
echo '<div class="form-group">'.$this->formRow($element).'</div>';
endforeach;

echo $this->form()->closeTag(); ?>



<?php
  if ($this->is_xmlhttprequest == 0) {
    echo '    </div>
    <!-- /.box-body -->
</div>';
}else{
    echo '</div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->';
}
?>
<script>
  $(function(){
    $("form#<?php echo $form->getName(); ?>").submit(function(){
         
        //if not call by ajax
        //submit to showformAction
        if ('<?php echo $this->is_xmlhttprequest; ?>' == 0) 
            return true;
        //if by ajax
        //check by ajax : validatepostajaxAction
        var progress = $(this).parent().find(".progress");
        $(progress).show();
        $.post("<?php echo $this->url($myRoute, array('controller'=>$myRoute, 'action'=>'validateajaxadd', 'id'=>$this->id)); ?>",
               $("form#<?php echo $form->getName(); ?>").serialize(), function(itemJson){
                 
                var error = false;
                 
                if (itemJson.success != 1){
                     
                    /*if ($(".element_name ul").length == 0){
                        //prepare ...
                        $(".element_name").append("<ul></ul>");
                    }
                     
                    for(var i=0;i<itemJson.name.length;i++)
                    {
                       if ($(".element_name ul").html().substr(itemJson.name[i]) == '')
                            $(".element_name ul").append('<li>'+itemJson.name[i]+'</li>');
                    }*/
                    
                    for(var j in itemJson)
                    {
                         if ($("form#<?php echo $form->getName(); ?> #" + j).parent().find("ul").length == 0){
                              //prepare ...
                              $("form#<?php echo $form->getName(); ?> #" + j).parent().append("<ul></ul>");
                          }
                         
                         //for(var i=0;i<itemJson[j].length;i++)
                         // {
                             if ($("form#<?php echo $form->getName(); ?> #" + j).parent().find("ul").html().substr(itemJson[j]) == '')
                                  $("form#<?php echo $form->getName(); ?> #" + j).parent().find("ul").append('<li>'+itemJson[j]+'</li>');
                         // }
                    }
                     
                    error = true;
                }
                 
                if (!error){
                    $("#ajaxadd").modal('hide');
                     
                    if (itemJson.success == 1){
                        $(progress).hide();
                        var myRef = "<?php echo $this->url($myRoute, array('controller'=>$myRoute, 'action'=>'ajaxtable', 'id'=>$this->id)); ?>";
                        var myObject = $("#ajaxtable");
                        if (myObject !== null) {
                            myObject.parent().append('<div class="overlay"><i class="fa fa-refresh fa-spin"></i></div>');
                            $(myObject).load(myRef, function() {
                             myObject.parent().find(".overlay").remove();
                            });
                        }
                    }
                }
                 
        }, 'json');
         
        return false;
    });
});  
</script>