<div class="box box-info">
    <div class="box-header">
      <h3 class="box-title">Редактировать</h3>
    </div>
    <div class="box-body">

<?php
$form = $this->form;
$form->prepare();
// Assuming the "contact/process" route exists...
//$form->setAttribute('action', $this->url('csn-cms/default', array('controller' => 'comment', 'action' => 'add'), true)); //'contact/process'));
// or
// $form->setAttribute('action', $this->url('grace-drops/default', array('controller' => 'translation', 'action' => 'add', 'id' => $this->id))); //'contact/process'));

// Set the method attribute for the form
$myRoute = $this->getHelperPluginManager()->getServiceLocator()->get('application')->getMvcEvent()->getRouteMatch()->getMatchedRouteName();
$form->setAttribute('action', $this->url($myRoute, array('controller' => $myRoute, 'action' => 'edit', 'id' => $this->id)));
$form->setAttribute('method', 'post');

echo $this->form(null,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL)->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag(); ?>

    </div>
    <!-- /.box-body -->
</div>

