<?php

$myRoute = $this->getHelperPluginManager()->getServiceLocator()->get('application')->getMvcEvent()->getRouteMatch()->getMatchedRouteName();
foreach ($this->data as $element){
    
    $ref = '<a href="'
      .$this->url($myRoute, array('controller'=>$myRoute, 'action'=>'view', 'id' => $element->getId())).'">'.$element->getName().'</a>';
    
    $tr .= '<tr>'.'<td>'.$element->getId().'</td>'.'<td>'.$ref.'</td>'.'<td>'.$element->getDescription().'</td>'.'</tr>';
} ?>

<?php
  if ($this->is_xmlhttprequest == 0)
    echo '<div class="row">
      <div class="col-md-12">
        <div id="area" class="box box-danger">
          <div class="box-header">
            <h3 class="box-title">Loading state</h3>
          </div>';
?>
<div class="box-body">
      <table class="table table-bordered">
        <tbody><tr>
          <th style="width: 10px">#</th>
          <th>Task</th>
          <th>Progress</th>
        </tr>
        <?php echo $tr; ?>
      </tbody></table>
    </div>
    <!-- /.box-body -->
    <div class="box-footer clearfix">
      <?php echo $this->paginationControl($this->data, 'sliding', 'inventory/partial/paginator.1.phtml', array('is_xmlhttprequest' => $this->is_xmlhttprequest,
      'w_id' => $this->w_id/*'id' => $this->id, 'name' => $myWidget['name']*/)); ?>
      </div>
      
      
      

<?php
if ($this->is_xmlhttprequest == 0)
    echo '
        </div>
        <!-- /.box -->
      </div>
    </div>';
?>