<?php

namespace DoctrineORMModule\Proxy\__CG__\Inventory\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DekaProgramms extends \Inventory\Entity\DekaProgramms implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'code', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'status', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'departmentid', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'notice', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'agenums', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'duration', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'ahours', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'billingtext', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'billingrules', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'flowagenums', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'edulevel');
        }

        return array('__isInitialized__', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'code', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'status', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'departmentid', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'notice', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'agenums', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'duration', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'ahours', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'billingtext', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'billingrules', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'flowagenums', '' . "\0" . 'Inventory\\Entity\\DekaProgramms' . "\0" . 'edulevel');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DekaProgramms $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', array());

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartmentid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartmentid', array());

        return parent::getDepartmentid();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartmentid($departmentid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartmentid', array($departmentid));

        return parent::setDepartmentid($departmentid);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotice', array());

        return parent::getNotice();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotice($notice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotice', array($notice));

        return parent::setNotice($notice);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgenums()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgenums', array());

        return parent::getAgenums();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgenums($agenums)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgenums', array($agenums));

        return parent::setAgenums($agenums);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuration', array());

        return parent::getDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuration($duration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuration', array($duration));

        return parent::setDuration($duration);
    }

    /**
     * {@inheritDoc}
     */
    public function getAhours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAhours', array());

        return parent::getAhours();
    }

    /**
     * {@inheritDoc}
     */
    public function setAhours($ahours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAhours', array($ahours));

        return parent::setAhours($ahours);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingtext()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingtext', array());

        return parent::getBillingtext();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingtext($billingtext)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingtext', array($billingtext));

        return parent::setBillingtext($billingtext);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingrules()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingrules', array());

        return parent::getBillingrules();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingrules($billingrules)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingrules', array($billingrules));

        return parent::setBillingrules($billingrules);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlowagenums()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlowagenums', array());

        return parent::getFlowagenums();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlowagenums($flowagenums)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlowagenums', array($flowagenums));

        return parent::setFlowagenums($flowagenums);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdulevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdulevel', array());

        return parent::getEdulevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdulevel($edulevel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdulevel', array($edulevel));

        return parent::setEdulevel($edulevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentid', array());

        return parent::getParentid();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentid($parentid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentid', array($parentid));

        return parent::setParentid($parentid);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedWhen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedWhen', array());

        return parent::getCreatedWhen();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedWhen($createdWhen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedWhen', array($createdWhen));

        return parent::setCreatedWhen($createdWhen);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedBy', array());

        return parent::getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedBy($modifiedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedBy', array($modifiedBy));

        return parent::setModifiedBy($modifiedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', array($data));

        return parent::exchangeArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

}
