<?php

namespace DoctrineORMModule\Proxy\__CG__\Inventory\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DekaAddresses extends \Inventory\Entity\DekaAddresses implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'parentid', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'type', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'postalcode', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'country', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'region', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'county', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'city', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'streetname', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'streettype', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'number', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'gate', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'floor', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'apartment', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'latitude', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'longitude', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'status');
        }

        return array('__isInitialized__', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'parentid', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'type', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'postalcode', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'country', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'region', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'county', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'city', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'streetname', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'streettype', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'number', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'gate', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'floor', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'apartment', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'latitude', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'longitude', '' . "\0" . 'Inventory\\Entity\\DekaAddresses' . "\0" . 'status');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DekaAddresses $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getParentid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentid', array());

        return parent::getParentid();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentid($parentid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentid', array($parentid));

        return parent::setParentid($parentid);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalcode', array());

        return parent::getPostalcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalcode($postalcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalcode', array($postalcode));

        return parent::setPostalcode($postalcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', array());

        return parent::getRegion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegion($region)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegion', array($region));

        return parent::setRegion($region);
    }

    /**
     * {@inheritDoc}
     */
    public function getCounty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCounty', array());

        return parent::getCounty();
    }

    /**
     * {@inheritDoc}
     */
    public function setCounty($county)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCounty', array($county));

        return parent::setCounty($county);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreetname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreetname', array());

        return parent::getStreetname();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreetname($streetname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreetname', array($streetname));

        return parent::setStreetname($streetname);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreettype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreettype', array());

        return parent::getStreettype();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreettype($streettype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreettype', array($streettype));

        return parent::setStreettype($streettype);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', array());

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', array($number));

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getGate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGate', array());

        return parent::getGate();
    }

    /**
     * {@inheritDoc}
     */
    public function setGate($gate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGate', array($gate));

        return parent::setGate($gate);
    }

    /**
     * {@inheritDoc}
     */
    public function getFloor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFloor', array());

        return parent::getFloor();
    }

    /**
     * {@inheritDoc}
     */
    public function setFloor($floor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFloor', array($floor));

        return parent::setFloor($floor);
    }

    /**
     * {@inheritDoc}
     */
    public function getApartment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApartment', array());

        return parent::getApartment();
    }

    /**
     * {@inheritDoc}
     */
    public function setApartment($apartment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApartment', array($apartment));

        return parent::setApartment($apartment);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', array());

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', array($latitude));

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', array());

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', array($longitude));

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedWhen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedWhen', array());

        return parent::getCreatedWhen();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedWhen($createdWhen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedWhen', array($createdWhen));

        return parent::setCreatedWhen($createdWhen);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedBy', array());

        return parent::getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedBy($modifiedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedBy', array($modifiedBy));

        return parent::setModifiedBy($modifiedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', array($data));

        return parent::exchangeArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

}
