DROP TABLE "AIRWAYFIDERS" CASCADE CONSTRAINTS
;

DROP TABLE "AIRWAYTYPES" CASCADE CONSTRAINTS
;

DROP TABLE "ALTFIDERS" CASCADE CONSTRAINTS
;

DROP TABLE "ALTFORMULAS" CASCADE CONSTRAINTS
;

DROP TABLE "AR_CFG_COLORS" CASCADE CONSTRAINTS
;

DROP TABLE "AR_CFG_COLUMNS" CASCADE CONSTRAINTS
;

DROP TABLE "AR_COLUMNS" CASCADE CONSTRAINTS
;

DROP TABLE "BILDATA" CASCADE CONSTRAINTS
;

DROP TABLE "CALC_ENERGY_TYPES" CASCADE CONSTRAINTS
;

DROP TABLE "CALC_LOG" CASCADE CONSTRAINTS
;

DROP TABLE "CALCDATA" CASCADE CONSTRAINTS
;

DROP TABLE "CATEGORIES_PS" CASCADE CONSTRAINTS
;

DROP TABLE "CHANNEL_CUSTOM_TYPES" CASCADE CONSTRAINTS
;

DROP TABLE "CHANNELDEVICES" CASCADE CONSTRAINTS
;

DROP TABLE "CHANNELS" CASCADE CONSTRAINTS
;

DROP TABLE "CHANNELS_COREL" CASCADE CONSTRAINTS
;

DROP TABLE "CHANNELS_CUSTOM" CASCADE CONSTRAINTS
;

DROP TABLE "CHANNELTYPES" CASCADE CONSTRAINTS
;

DROP TABLE "CHANNELVALUES" CASCADE CONSTRAINTS
;

DROP TABLE "COMMUNICATIONS" CASCADE CONSTRAINTS
;

DROP TABLE "CONNECTION_TYPES" CASCADE CONSTRAINTS
;

DROP TABLE "DATASNAP_SUBSCRIPTIONS" CASCADE CONSTRAINTS
;

DROP TABLE "DEVICECHANGE" CASCADE CONSTRAINTS
;

DROP TABLE "DEVICECHANGECHANNELS" CASCADE CONSTRAINTS
;

DROP TABLE "DEVICECHANGETYPES" CASCADE CONSTRAINTS
;

DROP TABLE "DEVICES" CASCADE CONSTRAINTS
;

DROP TABLE "DOCPROPS" CASCADE CONSTRAINTS
;

DROP TABLE "DST" CASCADE CONSTRAINTS
;

DROP TABLE "ENERGY_PRICE" CASCADE CONSTRAINTS
;

DROP TABLE "FORMFRACS" CASCADE CONSTRAINTS
;

DROP TABLE "FORMGROUPS" CASCADE CONSTRAINTS
;

DROP TABLE "FORMOPERANDS" CASCADE CONSTRAINTS
;

DROP TABLE "FORMTASKS" CASCADE CONSTRAINTS
;

DROP TABLE "FORMULAS" CASCADE CONSTRAINTS
;

DROP TABLE "FRACS" CASCADE CONSTRAINTS
;

DROP TABLE "GPRSTERMINALS" CASCADE CONSTRAINTS
;

DROP TABLE "GRAPH_GROUPS" CASCADE CONSTRAINTS
;

DROP TABLE "GRAPH_SERIES" CASCADE CONSTRAINTS
;

DROP TABLE "GRAPH_SERIES_GROUPS" CASCADE CONSTRAINTS
;

DROP TABLE "GRAPH_TRENDS" CASCADE CONSTRAINTS
;

DROP TABLE "GROUP_GROUPS" CASCADE CONSTRAINTS
;

DROP TABLE "GROUPS" CASCADE CONSTRAINTS
;

DROP TABLE "LIMITS" CASCADE CONSTRAINTS
;

DROP TABLE "MAKET_EXP_CODES" CASCADE CONSTRAINTS
;

DROP TABLE "MAKET_EXP_GROUPS" CASCADE CONSTRAINTS
;

DROP TABLE "MAKETCODES" CASCADE CONSTRAINTS
;

DROP TABLE "MAKETFORMATTYPES" CASCADE CONSTRAINTS
;

DROP TABLE "MAKETGROUPS" CASCADE CONSTRAINTS
;

DROP TABLE "MAKETS" CASCADE CONSTRAINTS
;

DROP TABLE "MAKETS_EXP" CASCADE CONSTRAINTS
;

DROP TABLE "MAKETSAVEDDATA" CASCADE CONSTRAINTS
;

DROP TABLE "MAKETTYPES" CASCADE CONSTRAINTS
;

DROP TABLE "MEASUREMENT_VALUE_SOURCES" CASCADE CONSTRAINTS
;

DROP TABLE "MIGRATION_HIST" CASCADE CONSTRAINTS
;

DROP TABLE "MOMDATA" CASCADE CONSTRAINTS
;

DROP TABLE "MSG_FILTERGROUPS" CASCADE CONSTRAINTS
;

DROP TABLE "MSG_FILTERS" CASCADE CONSTRAINTS
;

DROP TABLE "MSG_JOURNAL" CASCADE CONSTRAINTS
;

DROP TABLE "MSG_KVITNOTES" CASCADE CONSTRAINTS
;

DROP TABLE "MSG_KVITS" CASCADE CONSTRAINTS
;

DROP TABLE "MSG_SOURCES" CASCADE CONSTRAINTS
;

DROP TABLE "MSG_TEXTVALUES" CASCADE CONSTRAINTS
;

DROP TABLE "MSG_TYPES" CASCADE CONSTRAINTS
;

DROP TABLE "OLDCHANNELS" CASCADE CONSTRAINTS
;

DROP TABLE "OPERANDTYPES" CASCADE CONSTRAINTS
;

DROP TABLE "OPERATIONS" CASCADE CONSTRAINTS
;

DROP TABLE "OTPOSITION" CASCADE CONSTRAINTS
;

DROP TABLE "OWNERTYPES" CASCADE CONSTRAINTS
;

DROP TABLE "PERIODDELETE" CASCADE CONSTRAINTS
;

DROP TABLE "PROFDATA" CASCADE CONSTRAINTS
;

DROP TABLE "PROFDATA_SCD" CASCADE CONSTRAINTS
;

DROP TABLE "PROPERTIES" CASCADE CONSTRAINTS
;

DROP TABLE "PROPERTYDEVICES" CASCADE CONSTRAINTS
;

DROP TABLE "PROPERTYOWNERS" CASCADE CONSTRAINTS
;

DROP TABLE "PROPERTYTYPES" CASCADE CONSTRAINTS
;

DROP TABLE "PROPERTYVALUES" CASCADE CONSTRAINTS
;

DROP TABLE "QUALITY_TYPES" CASCADE CONSTRAINTS
;

DROP TABLE "REPORTARGUMENTS" CASCADE CONSTRAINTS
;

DROP TABLE "REPORTARGVALUES" CASCADE CONSTRAINTS
;

DROP TABLE "REPORTS" CASCADE CONSTRAINTS
;

DROP TABLE "REPORTTEMPLATES" CASCADE CONSTRAINTS
;

DROP TABLE "REPORTTREE" CASCADE CONSTRAINTS
;

DROP TABLE "ROUNDTYPES" CASCADE CONSTRAINTS
;

DROP TABLE "SEASONS" CASCADE CONSTRAINTS
;

DROP TABLE "SPR_CONNECT" CASCADE CONSTRAINTS
;

DROP TABLE "SPR_PS" CASCADE CONSTRAINTS
;

DROP TABLE "SPR_SUB" CASCADE CONSTRAINTS
;

DROP TABLE "SPR_THREADS" CASCADE CONSTRAINTS
;

DROP TABLE "SYS_BUFFER_PARAMS" CASCADE CONSTRAINTS
;

DROP TABLE "SYS_BUFFER_RESULTS" CASCADE CONSTRAINTS
;

DROP TABLE "SYS_DS_DEVICES" CASCADE CONSTRAINTS
;

DROP TABLE "SYS_DS_SERVERS" CASCADE CONSTRAINTS
;

DROP TABLE "SYS_SEMAFOR" CASCADE CONSTRAINTS
;

DROP TABLE "TARIFS" CASCADE CONSTRAINTS
;

DROP TABLE "TEST_AR_CFG_COLUNS" CASCADE CONSTRAINTS
;

DROP TABLE "TEST_TIME" CASCADE CONSTRAINTS
;

DROP TABLE "THREADS" CASCADE CONSTRAINTS
;

DROP TABLE "TIMEFORMATTYPES" CASCADE CONSTRAINTS
;

DROP TABLE "TRANSFIDERS_2W" CASCADE CONSTRAINTS
;

DROP TABLE "TRANSFIDERS_3W" CASCADE CONSTRAINTS
;

DROP TABLE "TRANSTYPES_2W" CASCADE CONSTRAINTS
;

DROP TABLE "TRANSTYPES_3W" CASCADE CONSTRAINTS
;

DROP TABLE "TYPEDEVICE" CASCADE CONSTRAINTS
;

DROP TABLE "UNITS" CASCADE CONSTRAINTS
;

DROP TABLE "UPPD" CASCADE CONSTRAINTS
;

DROP TABLE "USER_FIDERS" CASCADE CONSTRAINTS
;

DROP TABLE "USER_FORMULAS" CASCADE CONSTRAINTS
;

DROP TABLE "USER_IN_GROUPS" CASCADE CONSTRAINTS
;

DROP TABLE "USER_REPORTS" CASCADE CONSTRAINTS
;

DROP TABLE "USER_RIGHTS" CASCADE CONSTRAINTS
;

DROP TABLE "USER_STATE_OF_LIST" CASCADE CONSTRAINTS
;

DROP TABLE "USER_TASK_RIGHTS" CASCADE CONSTRAINTS
;

DROP TABLE "USER_TASKS" CASCADE CONSTRAINTS
;

DROP TABLE "USERGROUPS" CASCADE CONSTRAINTS
;

DROP TABLE "USERS" CASCADE CONSTRAINTS
;

DROP TABLE "VIRTUALTYPEDEVICE" CASCADE CONSTRAINTS
;

CREATE TABLE "AIRWAYFIDERS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE),
	"BASIC_FIDER_ID" NUMBER DEFAULT 0
	,
	"DUBL_FIDER_ID" NUMBER DEFAULT 0
	,
	"AIRWAY_ID" NUMBER DEFAULT 1
	,
	"LENGTH" FLOAT(126) DEFAULT 0
	,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL,
	"UN" FLOAT(126) DEFAULT 20  NOT NULL,
	"LENGTH_TO_SALE" FLOAT(126) DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "AIRWAYTYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(200 BYTE),
	"SECHENIE" NUMBER,
	"R0" FLOAT(126),
	"X0" FLOAT(126)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "ALTFIDERS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE),
	"FIDER_ID" NUMBER DEFAULT 0,
	"ALTFIDER_ID" NUMBER DEFAULT 0,
	"DATETIMESTART" DATE,
	"DATETIMEEND" DATE
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "ALTFORMULAS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE),
	"FORMULA_ID" NUMBER DEFAULT 0,
	"ALTFORMULA_ID" NUMBER DEFAULT 0,
	"DATETIMESTART" DATE,
	"DATETIMEEND" DATE
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "AR_CFG_COLORS"
(
	"USER_ID" NUMBER NOT NULL,
	"MSG_TYPE_ID" NUMBER NOT NULL,
	"COLOR" VARCHAR2(10 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "AR_CFG_COLUMNS"
(
	"USER_ID" NUMBER NOT NULL,
	"COLUMN_ID" NUMBER NOT NULL,
	"ISVISIBLE" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "AR_COLUMNS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(50 BYTE),
	"ISVISIBLE" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL,
	"FIELDS" VARCHAR2(50 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "BILDATA"
(
	"ARDTIMESTAMP" DATE,
	"FVALUE" FLOAT(126),
	"TYPEDATA" NUMBER,
	"DEVICEID" NUMBER,
	"TIMEFORMATTYPE" NUMBER DEFAULT 1
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		262144
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "CALC_ENERGY_TYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(100 BYTE),
	"DESCRIPTION" VARCHAR2(200 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "CALC_LOG"
(
	"FID" NUMBER,
	"ARDTIMESTAMP" DATE,
	"FTEXT" CLOB,
	"DEV_ID" NUMBER,
	"CHAN_ID" NUMBER,
	"ROUNDTYPE_ID" NUMBER,
	"PERIOD" NUMBER,
	"TIMEFORMATTYPE" NUMBER,
	"STARTDATE" DATE,
	"ENDDATE" DATE,
	"LOG_TYPE" NUMBER,
	"SESID" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		1048576
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "CALCDATA"
(
	"ARDTIMESTAMP" DATE,
	"FVALUE" FLOAT(126),
	"FORMULA_ID" NUMBER,
	"ROUNDTYPE_ID" NUMBER,
	"PERIOD" NUMBER,
	"TIMEFORMATTYPE" NUMBER,
	"SOURCE_ID" NUMBER DEFAULT 4
	,
	"QUALITY_ID" NUMBER DEFAULT 1
	,
	"IS_COEF" NUMBER DEFAULT 1
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		285212672
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "CATEGORIES_PS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "CHANNEL_CUSTOM_TYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE),
	"CHLTYPE_ID" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "CHANNELDEVICES"
(
	"CHL_ID" NUMBER NOT NULL,
	"TYPEDEVICE_ID" NUMBER NOT NULL,
	"OBISCODE" VARCHAR2(100 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "CHANNELS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE),
	"CHLTYPE_ID" NUMBER,
	"ST_CODE" NUMBER,
	"SHORTNAME" VARCHAR2(100 BYTE),
	"UNIT_ID" NUMBER,
	"IS_USE_LIMIT" NUMBER DEFAULT 0
	,
	"ORDER_ID" NUMBER DEFAULT 0
	,
	"IS_USE_TREND" NUMBER DEFAULT 1
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "CHANNELS_COREL"
(
	"CHL_ID_DIRECT" NUMBER,
	"CHL_ID_REVERSE" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "CHANNELS_CUSTOM"
(
	"USER_ID" NUMBER,
	"CHL_CUSTOM_TYPE_ID" NUMBER,
	"CHL_ID" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "CHANNELTYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(100 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "CHANNELVALUES"
(
	"FID" NUMBER NOT NULL,
	"DEVICE_ID" NUMBER,
	"CHL_ID" NUMBER,
	"ACTIVE" NUMBER DEFAULT 1  NOT NULL,
	"CRON" VARCHAR2(2000 BYTE) DEFAULT '* * * * * *'  NOT NULL,
	"COUNTWORK" NUMBER DEFAULT 3  NOT NULL,
	"DATETIMESTART" DATE DEFAULT sysdate  NOT NULL,
	"NEXTWORK" DATE,
	"VISUALSCALER" NUMBER DEFAULT 1  NOT NULL,
	"TIMEFORMATTYPE" NUMBER DEFAULT 1  NOT NULL,
	"ROUNDFACTOR" NUMBER DEFAULT 10
	 NOT NULL,
	"ROUNDINGTYPE" NUMBER DEFAULT 1  NOT NULL,
	"IS_STORED" NUMBER DEFAULT 1 NOT NULL,
	"MIN_FREQ_VALUES" NUMBER DEFAULT 0
	 NOT NULL,
	"DEPTH_VALUES" NUMBER DEFAULT 365  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		851968
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "COMMUNICATIONS"
(
	"FID" NUMBER NOT NULL,
	"GROUP_ID" NUMBER,
	"ACTIVE" NUMBER DEFAULT 1,
	"NUMBER_RESERVE" NUMBER,
	"CONNECTTYPE" NUMBER,
	"CONNECTVALUE" VARCHAR2(40 BYTE),
	"SPEED" NUMBER,
	"READTIMEOUT" NUMBER DEFAULT 1000  NOT NULL,
	"IOTIMEQUOTA" NUMBER DEFAULT 50  NOT NULL,
	"REMOTE_PORT" NUMBER DEFAULT 4003  NOT NULL,
	"READINTERVALTIMEOUT" NUMBER DEFAULT 100  NOT NULL,
	"READTOTALTIMEOUTMULTIPLIER" NUMBER DEFAULT 0  NOT NULL,
	"READTOTALTIMEOUTCONSTANT" NUMBER DEFAULT 2000  NOT NULL,
	"WRITETOTALTIMEOUTMULTIPLIER" NUMBER DEFAULT 0  NOT NULL,
	"WRITETOTALTIMEOUTCONSTANT" NUMBER DEFAULT 0  NOT NULL,
	"LOCAL_PORT" NUMBER DEFAULT 0
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "CONNECTION_TYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "DATASNAP_SUBSCRIPTIONS"
(
	"FID" NUMBER NOT NULL,
	"USER_ID" NUMBER DEFAULT 0,
	"DEVICE_ID" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "DEVICECHANGE"
(
	"RID" NUMBER NOT NULL,
	"DEVICE_ID" NUMBER,
	"REM_SERIAL" VARCHAR2(16 BYTE),
	"REM_TN" NUMBER,
	"REM_TT" NUMBER,
	"REM_DATE" DATE,
	"SET_SERIAL" VARCHAR2(16 BYTE),
	"SET_TN" NUMBER,
	"SET_TT" NUMBER,
	"SET_DATE" DATE,
	"CHANGENOTE" VARCHAR2(255 BYTE),
	"USER_ID" NUMBER,
	"REM_TYPEDEVICE_ID" NUMBER,
	"SET_TYPEDEVICE_ID" NUMBER,
	"REM_PHYSICALID" NUMBER,
	"SET_PHYSICALID" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "DEVICECHANGECHANNELS"
(
	"DEVCHANGE_ID" NUMBER,
	"DEVCHANGETYPE_ID" NUMBER DEFAULT 0,
	"CHL_ID" NUMBER,
	"FVALUE" FLOAT(126) DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "DEVICECHANGETYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "DEVICES"
(
	"ID" NUMBER NOT NULL,
	"GROUPID" NUMBER,
	"DISPNAME" VARCHAR2(120 BYTE),
	"ACTIVE" NUMBER,
	"TYPEDEVICE_ID" NUMBER,
	"LINKTOFIDER" NUMBER,
	"PASSFORREADING" VARCHAR2(8 BYTE) DEFAULT '00000000'
	,
	"LOGICALID" NUMBER,
	"PHYSICALID" NUMBER,
	"PERIOD" NUMBER,
	"CLIENTTYPE" NUMBER DEFAULT 32  NOT NULL,
	"VIRTUALTYPEDEVICE_ID" NUMBER,
	"KTN" NUMBER DEFAULT 1,
	"KTT" NUMBER DEFAULT 1,
	"SERIALNUM" NUMBER DEFAULT 0,
	"KOEFINDEV" NUMBER DEFAULT 0,
	"DIRECTENERGY" NUMBER DEFAULT 1  NOT NULL,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL,
	"PASSFORWRITING" VARCHAR2(8 BYTE) DEFAULT '00000000'
	,
	"KTPE" NUMBER DEFAULT 1
	,
	"ACCESSLEVEL" NUMBER DEFAULT 1  NOT NULL,
	"PRIORITY" NUMBER DEFAULT 0  NOT NULL,
	"CUSTOM_PERIOD" NUMBER DEFAULT 1800  NOT NULL,
	"CALC_ENERGY_TYPE" NUMBER DEFAULT 1  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "DOCPROPS"
(
	"DOCID" NUMBER,
	"ID" NUMBER,
	"FNAME" VARCHAR2(20 BYTE),
	"FTYPE" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "DST"
(
	"YEAR" NUMBER(4) NOT NULL,
	"DSTS" DATE NOT NULL,
	"DSTE" DATE NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "ENERGY_PRICE"
(
	"CHL_ID" NUMBER NOT NULL,
	"PRICE" FLOAT(126)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "FORMFRACS"
(
	"ARDTIMESTAMP" DATE,
	"FORMULA_ID" NUMBER,
	"PERIOD" NUMBER,
	"FVALUE" FLOAT(126),
	"TIMEFORMATTYPE" NUMBER,
	"ROUNDTYPE" NUMBER,
	"IS_COEF" NUMBER DEFAULT 1
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		5242880
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "FORMGROUPS"
(
	"FID" NUMBER NOT NULL,
	"PARENT_ID" NUMBER,
	"FNAME" VARCHAR2(100 BYTE),
	"ORDER_ID" NUMBER DEFAULT 0
	 NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "FORMOPERANDS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(200 BYTE) NOT NULL,
	"OPERANDTYPE_ID" NUMBER NOT NULL,
	"DEVICE_ID" NUMBER,
	"CHL_ID" NUMBER,
	"FORMULA_ID" NUMBER,
	"ROUNDTYPE_ID" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL,
	"DEFAULTVALUE" FLOAT(126) DEFAULT 0  NOT NULL,
	"ISLOSSES" NUMBER DEFAULT 0
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "FORMTASKS"
(
	"FID" NUMBER NOT NULL,
	"FORMULA_ID" NUMBER,
	"DATETIMEFROM" DATE,
	"DATETIMETO" DATE
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		2097152
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "FORMULAS"
(
	"FID" NUMBER NOT NULL,
	"GROUP_ID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(200 BYTE) NOT NULL,
	"PERIOD" NUMBER NOT NULL,
	"FORMULA" VARCHAR2(4000 BYTE),
	"ROUNDTYPE_ID" NUMBER,
	"ISACTIVE" NUMBER DEFAULT 1  NOT NULL,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL,
	"TIMEFORMATTYPE" NUMBER DEFAULT 1  NOT NULL,
	"LASTREAD" DATE,
	"USE_ALT" NUMBER DEFAULT 0  NOT NULL,
	"UNIT_ID" NUMBER DEFAULT 2  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "FRACS"
(
	"ARDTIMESTAMP" DATE NOT NULL,
	"DEVICE_ID" NUMBER,
	"CHANNEL_ID" NUMBER,
	"PERIOD" NUMBER,
	"FVALUE" FLOAT(126),
	"ROUNDTYPE" NUMBER,
	"IS_COEF" NUMBER DEFAULT 0
	,
	"IS_LOSSES" NUMBER DEFAULT 0
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		20971520
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "GPRSTERMINALS"
(
	"ID" NUMBER(38) NOT NULL,
	"IMEI" VARCHAR2(30 BYTE) NOT NULL,
	"COMPORTNAME" VARCHAR2(30 BYTE),
	"GROUPID" NUMBER(38)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "GRAPH_GROUPS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE),
	"PARENT_ID" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL,
	"USER_ID" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "GRAPH_SERIES"
(
	"FID" NUMBER NOT NULL,
	"GROUP_ID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE),
	"DEVICE_ID" NUMBER DEFAULT 0 NOT NULL,
	"CHL_ID" NUMBER DEFAULT 0
	 NOT NULL,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "GRAPH_SERIES_GROUPS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE),
	"PARENT_ID" NUMBER,
	"ORDER_ID" NUMBER,
	"TREND_ID" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "GRAPH_TRENDS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE),
	"GROUP_ID" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "GROUP_GROUPS"
(
	"FID" NUMBER NOT NULL,
	"PARENT_ID" NUMBER,
	"FNAME" VARCHAR2(255 BYTE),
	"ORDER_ID" NUMBER DEFAULT 0
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "GROUPS"
(
	"ID" NUMBER NOT NULL,
	"CONNECTTYPE" NUMBER,
	"CONNECTVALUE" VARCHAR2(40 BYTE),
	"SPEED" NUMBER,
	"DISPNAME" VARCHAR2(120 BYTE),
	"ACTIVE" NUMBER,
	"BLOCKACTIVE" NUMBER,
	"BLOCKCOUNT" NUMBER,
	"BLOCKMIN" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL,
	"READTIMEOUT" NUMBER DEFAULT 1000  NOT NULL,
	"IOTIMEQUOTA" NUMBER DEFAULT 50  NOT NULL,
	"REMOTE_PORT" NUMBER DEFAULT 4003  NOT NULL,
	"PRIORITY" NUMBER DEFAULT 0  NOT NULL,
	"READINTERVALTIMEOUT" NUMBER DEFAULT 100  NOT NULL,
	"READTOTALTIMEOUTMULTIPLIER" NUMBER DEFAULT 0  NOT NULL,
	"READTOTALTIMEOUTCONSTANT" NUMBER DEFAULT 2000  NOT NULL,
	"WRITETOTALTIMEOUTMULTIPLIER" NUMBER DEFAULT 0  NOT NULL,
	"WRITETOTALTIMEOUTCONSTANT" NUMBER DEFAULT 0  NOT NULL,
	"LOCAL_PORT" NUMBER DEFAULT 0,
	"ACTION_BEFORE_LOCK" VARCHAR2(500 BYTE),
	"GROUP_ID" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "LIMITS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(120 BYTE),
	"OWNER_ID" NUMBER,
	"CHL_ID" NUMBER,
	"TARIF_ID" NUMBER,
	"STARTDAY" DATE,
	"ENDDAY" DATE,
	"STARTTIME" DATE,
	"ENDTIME" DATE,
	"FVALUE" FLOAT(126),
	"OWNERTYPE_ID" NUMBER,
	"PERIOD" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		4194304
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MAKET_EXP_CODES"
(
	"FID" NUMBER NOT NULL,
	"MAKET_ID" NUMBER,
	"FNAME" VARCHAR2(255 BYTE),
	"FCODE" VARCHAR2(255 BYTE),
	"DEVICE_ID" NUMBER,
	"ROUNDTYPE_ID" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL,
	"IS_USE_COEF" NUMBER DEFAULT 1
	,
	"LINK_TYPE_ID" NUMBER DEFAULT 1
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MAKET_EXP_GROUPS"
(
	"FID" NUMBER NOT NULL,
	"PARENT_ID" NUMBER,
	"FNAME" VARCHAR2(255 BYTE),
	"ORDER_ID" NUMBER DEFAULT 0
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MAKETCODES"
(
	"FID" NUMBER NOT NULL,
	"MAKET_ID" NUMBER,
	"FNAME" VARCHAR2(255 BYTE),
	"FCODE" VARCHAR2(255 BYTE),
	"DEVICE_ID" NUMBER,
	"CHL_ID" NUMBER,
	"ROUNDTYPE_ID" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MAKETFORMATTYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MAKETGROUPS"
(
	"FID" NUMBER NOT NULL,
	"PARENT_ID" NUMBER,
	"FNAME" VARCHAR2(255 BYTE),
	"ORDER_ID" NUMBER DEFAULT 0
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MAKETS"
(
	"FID" NUMBER NOT NULL,
	"GROUP_ID" NUMBER,
	"FNAME" VARCHAR2(255 BYTE),
	"FORMATTYPE" NUMBER,
	"MAKETTYPE" NUMBER,
	"TIMEFORMATTYPE" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL,
	"ISACTIVE" NUMBER DEFAULT 1  NOT NULL,
	"PERIOD" NUMBER DEFAULT 1800  NOT NULL,
	"EMAILSENDER" VARCHAR2(255 BYTE) DEFAULT ''  NOT NULL,
	"FILTERBYSENDER" NUMBER DEFAULT 0  NOT NULL,
	"SUBJECTLINE" VARCHAR2(255 BYTE) DEFAULT ''  NOT NULL,
	"FILTERBYSUBJECTLINE" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MAKETS_EXP"
(
	"FID" NUMBER NOT NULL,
	"GROUP_ID" NUMBER,
	"FNAME" VARCHAR2(255 BYTE),
	"FORMATTYPE" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL,
	"ISACTIVE" NUMBER DEFAULT 1  NOT NULL,
	"EMAIL_SENDER" VARCHAR2(255 BYTE) DEFAULT null
	 NOT NULL,
	"SUBJECTLINE" VARCHAR2(255 BYTE) DEFAULT null
	 NOT NULL,
	"EMAIL_TO" VARCHAR2(255 BYTE) NOT NULL,
	"EMAIL_ADMIN" VARCHAR2(255 BYTE),
	"FROMLINE" VARCHAR2(255 BYTE),
	"MAKET_HEADER" VARCHAR2(255 BYTE),
	"FILE_NAME" VARCHAR2(255 BYTE),
	"IS_ATTACH" NUMBER DEFAULT 1
	,
	"IS_ARCHIVE" NUMBER DEFAULT 0
	,
	"IS_SEND_NOT_FULL" NUMBER DEFAULT 1
	,
	"IS_SEND_COMMENT" NUMBER DEFAULT 0
	,
	"IS_USE_ASC_CODE" NUMBER DEFAULT 0
	,
	"IS_FINAL_MAKET" NUMBER DEFAULT 0
	,
	"IS_USE_QUADRANTS" NUMBER DEFAULT 1
	,
	"IS_USE_BILING" NUMBER DEFAULT 0
	,
	"IS_REPORT_ALARM" NUMBER DEFAULT 1
	,
	"IS_SEND_TO_ADMIN" NUMBER DEFAULT 0
	,
	"IS_CHECK_NDR" NUMBER DEFAULT 0
	,
	"NDR_COUNT_TEST_REQ" NUMBER DEFAULT 2
	,
	"NDR_PAUSE_REQ" NUMBER DEFAULT 10
	,
	"NDR_DELAY_BEFORE_TEST" NUMBER DEFAULT 30
	,
	"NDR_RESEND_COUNT" NUMBER DEFAULT 2
	,
	"IS_SEND_TO_SMTP" NUMBER DEFAULT 1
	,
	"IS_SEND_TO_FTP" NUMBER DEFAULT 0
	,
	"FILENAME_PREFIX_FTP" VARCHAR2(255 BYTE) DEFAULT 'aase'
	,
	"CRON" VARCHAR2(2000 BYTE) DEFAULT '0 0 7 * * *'
	 NOT NULL,
	"DATETIMESTART" DATE DEFAULT sysdate  NOT NULL,
	"NEXTWORK" DATE
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MAKETSAVEDDATA"
(
	"MID" NUMBER NOT NULL,
	"ARDTIMESTAMP" DATE,
	"MDATATYPE" NUMBER NOT NULL,
	"INTPERIOD" FLOAT(126) NOT NULL,
	"VALNOM" NUMBER NOT NULL,
	"VAL" FLOAT(126)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MAKETTYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MEASUREMENT_VALUE_SOURCES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(100 BYTE),
	"DESCRIPTION" VARCHAR2(255 BYTE),
	"COLOR" VARCHAR2(100 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MIGRATION_HIST"
(
	"FID" NUMBER NOT NULL,
	"MAJOR_VERSION" VARCHAR2(3 BYTE),
	"MINOR_VERSION" VARCHAR2(3 BYTE),
	"RELEASE" VARCHAR2(3 BYTE),
	"FILE_NUMBER" VARCHAR2(4 BYTE),
	"DESCRIPTION" VARCHAR2(255 BYTE),
	"DATE_APPLIED" DATE DEFAULT sysdate
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MOMDATA"
(
	"ARDTIMESTAMP" DATE,
	"FVALUE" FLOAT(126),
	"TYPEDATA" NUMBER,
	"DEVICEID" NUMBER,
	"TIMEFORMATTYPE" NUMBER DEFAULT 1
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		4194304
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MSG_FILTERGROUPS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(200 BYTE),
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL,
	"USER_ID" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MSG_FILTERS"
(
	"FID" NUMBER NOT NULL,
	"GROUP_ID" NUMBER,
	"USER_ID" NUMBER,
	"FNAME" VARCHAR2(200 BYTE),
	"SUBJECT_ID" NUMBER,
	"SUBSTATION_ID" NUMBER,
	"FIDER_ID" NUMBER,
	"CATEGORY_PS_ID" NUMBER,
	"MSG_TYPE_ID" NUMBER,
	"MSG_TEXT_ID" NUMBER,
	"MSG_TEXT_MASK" VARCHAR2(100 BYTE),
	"DTWRTDBFROM" DATE,
	"DTWRTDBTO" DATE,
	"SLIDWRTDBOP" NUMBER,
	"SLIDWRTDBCOUNT" NUMBER,
	"SLIDWRTDBUNIT" NUMBER,
	"DTHWFROM" DATE,
	"DTHWTO" DATE,
	"SLIDHWOP" NUMBER,
	"SLIDHWCOUNT" NUMBER,
	"SLIDHWUNIT" NUMBER,
	"RULES" NUMBER,
	"ORDER_ID" NUMBER,
	"ISACTIVE" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MSG_JOURNAL"
(
	"FID" NUMBER NOT NULL,
	"DTWRTDB" DATE DEFAULT sysdate  NOT NULL,
	"DTHARDWARE" DATE,
	"MSG_TEXT_ID" NUMBER,
	"MSG_TYPE_ID" NUMBER,
	"FIDER_ID" NUMBER,
	"CHL_ID" NUMBER,
	"MSG_VALUE" VARCHAR2(500 BYTE) DEFAULT 0
	,
	"SOURCE_ID" NUMBER DEFAULT 0
	,
	"USER_ID" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		39845888
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MSG_KVITNOTES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(500 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MSG_KVITS"
(
	"FID" NUMBER NOT NULL,
	"JOURNAL_ID" NUMBER,
	"DTKVIT" DATE,
	"KVITNOTE_ID" NUMBER,
	"USER_ID" NUMBER,
	"COMMENTS" VARCHAR2(500 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MSG_SOURCES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MSG_TEXTVALUES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(500 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "MSG_TYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(50 BYTE),
	"DESCRIPTION" VARCHAR2(200 BYTE),
	"COLOR" VARCHAR2(10 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "OLDCHANNELS"
(
	"CHL_ID" NUMBER NOT NULL,
	"OLDCHL_ID" NUMBER NOT NULL,
	"OLDCHL_NAME" VARCHAR2(255 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "OPERANDTYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(50 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "OPERATIONS"
(
	"FID" NUMBER,
	"FNAME" VARCHAR2(100 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "OTPOSITION"
(
	"ID" NUMBER NOT NULL,
	"NAME_TYPE_MESSAGE" VARCHAR2(1 BYTE),
	"TOP" NUMBER,
	"left" NUMBER,
	"WIDTH" NUMBER,
	"HEIGHT" NUMBER,
	"NAMEUSER" VARCHAR2(45 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "OWNERTYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(100 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "PERIODDELETE"
(
	"ID" NUMBER NOT NULL,
	"AFILTER" VARCHAR2(45 BYTE),
	"LASTDELETE" TIMESTAMP(6)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "PROFDATA"
(
	"DEVICEID" NUMBER,
	"ARDTIMESTAMP" DATE,
	"TYPEDATA" NUMBER,
	"FVALUE" FLOAT(126),
	"TIMEFORMATTYPE" NUMBER DEFAULT 1
	,
	"PERIOD" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		34603008
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "PROFDATA_SCD"
(
	"DEVICEID" NUMBER,
	"ARDTIMESTAMP" DATE,
	"TYPEDATA" NUMBER,
	"FVALUE" NUMBER,
	"PERIOD" NUMBER,
	"SOURCE_ID" NUMBER DEFAULT 1
	,
	"QUALITY_ID" NUMBER DEFAULT 1
	,
	"ROUND_TYPE_ID" NUMBER DEFAULT 0
	,
	"IS_COEF" NUMBER DEFAULT 0
	,
	"IS_LOSSES" NUMBER DEFAULT 0
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		34603008
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "PROPERTIES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(100 BYTE),
	"PTYPE" NUMBER NOT NULL,
	"DEFULTVALUE" VARCHAR2(200 BYTE),
	"PARENT_ID" NUMBER DEFAULT 0  NOT NULL,
	"MAXLENGTH" NUMBER DEFAULT 255  NOT NULL,
	"MAXINT" NUMBER DEFAULT 2147483647  NOT NULL,
	"MININT" NUMBER DEFAULT -2147483648  NOT NULL,
	"MAXFLOAT" FLOAT(126) DEFAULT 2147483647  NOT NULL,
	"MINFLOAT" FLOAT(126) DEFAULT -2147483648  NOT NULL,
	"FREADONLY" NUMBER DEFAULT 0,
	"DESCRIPTION" VARCHAR2(200 BYTE),
	"ORDER_ID" NUMBER DEFAULT 0
	
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "PROPERTYDEVICES"
(
	"DEVICETYPE_ID" NUMBER(6) NOT NULL,
	"PROPERTY_ID" NUMBER(6) NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "PROPERTYOWNERS"
(
	"OWNERTYPE_ID" NUMBER NOT NULL,
	"PROPERTY_ID" NUMBER NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "PROPERTYTYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(100 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "PROPERTYVALUES"
(
	"OWNER_ID" NUMBER NOT NULL,
	"OWNERTYPE_ID" NUMBER NOT NULL,
	"PROPERTY_ID" NUMBER NOT NULL,
	"PVALUE" VARCHAR2(255 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "QUALITY_TYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(50 BYTE),
	"DESCRIPTION" VARCHAR2(255 BYTE),
	"COLOR" VARCHAR2(100 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "REPORTARGUMENTS"
(
	"FID" NUMBER NOT NULL,
	"TEMPLATE_ID" NUMBER DEFAULT 0
	,
	"ARGNAME" VARCHAR2(50 BYTE),
	"CATEGORYNAME" VARCHAR2(20 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "REPORTARGVALUES"
(
	"REPORT_ID" NUMBER NOT NULL,
	"ARG_ID" NUMBER NOT NULL,
	"FVALUE" CHAR(200 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "REPORTS"
(
	"FID" NUMBER NOT NULL,
	"TEMPLATE_ID" NUMBER,
	"IS_SHOW_MAP_FIDERS" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "REPORTTEMPLATES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "REPORTTREE"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE),
	"PARENT_ID" NUMBER,
	"PARENTTREE_ID" NUMBER,
	"REPORT_ID" NUMBER,
	"ORDER_ID" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "ROUNDTYPES"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(100 BYTE),
	"FDESCRIPTION" VARCHAR2(500 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "SEASONS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE),
	"STARTDAY" DATE,
	"ENDDAY" DATE,
	"ORDER_ID" NUMBER DEFAULT 0
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "SPR_CONNECT"
(
	"ID" NUMBER NOT NULL,
	"DISPNAME" VARCHAR2(120 BYTE),
	"ST_CODE" NUMBER,
	"ID_PS" NUMBER,
	"ID_SUB" NUMBER,
	"OPERATION_ID" NUMBER DEFAULT 1  NOT NULL,
	"ISCALCLIMIT" NUMBER DEFAULT 0  NOT NULL,
	"ISCALCPROF" NUMBER DEFAULT 0  NOT NULL,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL,
	"USE_ALT" NUMBER DEFAULT 0  NOT NULL,
	"USE_PREV_DATA_MI" NUMBER DEFAULT 0  NOT NULL,
	"USE_STD_REPORT" NUMBER DEFAULT 1  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "SPR_PS"
(
	"ID" NUMBER NOT NULL,
	"DISPNAME" VARCHAR2(120 BYTE),
	"ST_CODE" NUMBER,
	"ID_SUB" NUMBER,
	"OPERATION_ID" NUMBER,
	"ISCALCLIMIT" NUMBER,
	"ISCALCPROF" NUMBER,
	"CATEGORY_PS_ID" NUMBER DEFAULT 0
	 NOT NULL,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "SPR_SUB"
(
	"ID" NUMBER NOT NULL,
	"DISPNAME" VARCHAR2(120 BYTE),
	"ST_CODE" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "SPR_THREADS"
(
	"ID" NUMBER NOT NULL,
	"THREADID" NUMBER,
	"GROUPID" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "SYS_BUFFER_PARAMS"
(
	"ID" NUMBER(10) NOT NULL,
	"PARAMS" NVARCHAR2(50) NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "SYS_BUFFER_RESULTS"
(
	"ID" NUMBER(10) NOT NULL,
	"PARAMS" NVARCHAR2(50) NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "SYS_DS_DEVICES"
(
	"ID_A1" NUMBER(10) NOT NULL,
	"ID_DS_A1" NUMBER(10) NOT NULL,
	"ORIGINALID" NUMBER(10) NOT NULL,
	"DEVICEID" NUMBER(10) NOT NULL,
	"DEVICE_NAME" NVARCHAR2(50),
	"IS_SHEDULER" NUMBER(10),
	"IS_SUBSCRIPT" NUMBER(10),
	"MASKCRON" NVARCHAR2(250),
	"MASKCRONDEF" NVARCHAR2(250)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "SYS_DS_SERVERS"
(
	"ID" NUMBER(10) NOT NULL,
	"ALIAS" NVARCHAR2(25) NOT NULL,
	"HOST" NVARCHAR2(25) NOT NULL,
	"PORT" NVARCHAR2(15) NOT NULL,
	"PROTOCOL" NVARCHAR2(15) NOT NULL,
	"LOGIN" NVARCHAR2(25) NOT NULL,
	"PASSWORD" NVARCHAR2(25) NOT NULL,
	"IS_USE" NUMBER(10) NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "SYS_SEMAFOR"
(
	"ID" NUMBER(10) NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "TARIFS"
(
	"FID" NUMBER NOT NULL,
	"SEASON_ID" NUMBER,
	"FNAME" VARCHAR2(255 BYTE),
	"COLOR" VARCHAR2(10 BYTE),
	"STARTTIME" DATE,
	"ENDTIME" DATE,
	"COEF" FLOAT(126) DEFAULT 1  NOT NULL,
	"STARTDAY" DATE,
	"ENDDAY" DATE,
	"ISACTIVE" NUMBER DEFAULT 1
	,
	"ORDER_ID" NUMBER DEFAULT 0
	,
	"FNUMBER" NUMBER DEFAULT 1  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "TEST_AR_CFG_COLUNS"
(
	"USER_ID" NUMBER(6) NOT NULL,
	"COLUMN_ID" NUMBER(3) NOT NULL,
	"ISVISIBLE" NUMBER(1) NOT NULL,
	"COLUMNS_NAME" VARCHAR2(100 BYTE) NOT NULL,
	"ORDER_ID" NUMBER(3) NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "TEST_TIME"
(
	"FVAL" NUMBER,
	"LOC_TIMEZONE" TIMESTAMP(6) WITH LOCAL TIME ZONE,
	"TIMEZONE" TIMESTAMP(6) WITH TIME ZONE
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "THREADS"
(
	"ID" NUMBER NOT NULL,
	"DISPNAME" VARCHAR2(30 BYTE),
	"ACTIVE" NUMBER,
	"COMPORT" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL,
	"COMPORT_RESERVE" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "TIMEFORMATTYPES"
(
	"TIMEFORMATTYPE" NUMBER NOT NULL,
	"DISPNAME" VARCHAR2(3 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "TRANSFIDERS_2W"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE),
	"FIDER_ID" NUMBER,
	"TRANSTYPE_ID" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "TRANSFIDERS_3W"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(255 BYTE),
	"FIDER_ID" NUMBER,
	"TRANSTYPE_ID" NUMBER,
	"ORDER_ID" NUMBER DEFAULT 0  NOT NULL
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "TRANSTYPES_2W"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(200 BYTE),
	"SN" FLOAT(126),
	"DP_XX" FLOAT(126),
	"DP_KZ" FLOAT(126),
	"U_KZ" FLOAT(126),
	"I_XX" FLOAT(126)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "TRANSTYPES_3W"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(200 BYTE),
	"SN" FLOAT(126),
	"UN_VN" FLOAT(126),
	"UN_SN" FLOAT(126),
	"UN_NN" FLOAT(126),
	"S_VN" FLOAT(126),
	"S_SN" FLOAT(126),
	"S_NN" FLOAT(126),
	"DP_VN" FLOAT(126),
	"DP_SN" FLOAT(126),
	"DP_NN" FLOAT(126),
	"I_XX" FLOAT(126)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "TYPEDEVICE"
(
	"ID" NUMBER NOT NULL,
	"TYPENAME" VARCHAR2(40 BYTE),
	"ST_CODE" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "UNITS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(120 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "UPPD"
(
	"CODESUBJ" VARCHAR2(50 BYTE),
	"CODECHAN" VARCHAR2(50 BYTE),
	"CODEOBJ" VARCHAR2(50 BYTE),
	"CHANNAME" VARCHAR2(50 BYTE),
	"ARDTIMESTAMP" DATE,
	"DATAVALUES" VARCHAR2(255 BYTE),
	"SUMMA" VARCHAR2(50 BYTE),
	"H1" FLOAT(126),
	"H2" FLOAT(126),
	"H3" FLOAT(126),
	"H4" FLOAT(126),
	"H5" FLOAT(126),
	"H6" FLOAT(126),
	"H7" FLOAT(126),
	"H8" FLOAT(126),
	"H9" FLOAT(126),
	"H10" FLOAT(126),
	"H11" FLOAT(126),
	"H12" FLOAT(126),
	"H13" FLOAT(126),
	"H14" FLOAT(126),
	"H15" FLOAT(126),
	"H16" FLOAT(126),
	"H17" FLOAT(126),
	"H18" FLOAT(126),
	"H19" FLOAT(126),
	"H20" FLOAT(126),
	"H21" FLOAT(126),
	"H22" FLOAT(126),
	"H23" FLOAT(126),
	"H24" FLOAT(126),
	"H25" FLOAT(126),
	"OSTATOK" FLOAT(126),
	"ISPREVDAYOSTATOKADDED" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		131072
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "USER_FIDERS"
(
	"FID" NUMBER NOT NULL,
	"GROUP_ID" NUMBER,
	"FIDER_ID" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "USER_FORMULAS"
(
	"FID" NUMBER NOT NULL,
	"GROUP_ID" NUMBER,
	"FORMULA_ID" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "USER_IN_GROUPS"
(
	"FID" NUMBER NOT NULL,
	"USER_ID" NUMBER,
	"GROUP_ID" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "USER_REPORTS"
(
	"FID" NUMBER NOT NULL,
	"GROUP_ID" NUMBER,
	"REPORT_ID" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "USER_RIGHTS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(100 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "USER_STATE_OF_LIST"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(100 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "USER_TASK_RIGHTS"
(
	"FID" NUMBER NOT NULL,
	"GROUP_ID" NUMBER,
	"TASK_ID" NUMBER,
	"RIGHT_MASK" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "USER_TASKS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(200 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "USERGROUPS"
(
	"FID" NUMBER NOT NULL,
	"FNAME" VARCHAR2(50 BYTE),
	"FDESCRIPTION" VARCHAR2(500 BYTE),
	"ISACTIVE" VARCHAR2(5 BYTE),
	"IMAGE_ID" NUMBER,
	"FIDER_STATE_ID" NUMBER,
	"REPORT_STATE_ID" NUMBER,
	"FORMULA_STATE_ID" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "USERS"
(
	"FID" NUMBER NOT NULL,
	"GROUP_ID" NUMBER DEFAULT 1 NOT NULL,
	"ISACTIVE" VARCHAR2(5 BYTE),
	"LOGIN" VARCHAR2(20 BYTE),
	"FULLNAME" VARCHAR2(50 BYTE),
	"FDESCRIPTION" VARCHAR2(200 BYTE),
	"PASS" VARCHAR2(32 BYTE)
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE TABLE "VIRTUALTYPEDEVICE"
(
	"ID" NUMBER NOT NULL,
	"TYPENAME" VARCHAR2(60 CHAR),
	"ST_CODE" NUMBER
)
TABLESPACE	USERS
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

CREATE INDEX "FK_AIRWAYFIDERS_AIRWAY_ID"   
 ON "AIRWAYFIDERS" ("AIRWAY_ID") 
LOGGING
TABLESPACE	USERS
PCTFREE		10
INITRANS	2
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
NOPARALLEL
;

CREATE OR REPLACE TRIGGER "TRG_DEL_ON_AIRWAYFIDERS" 
AFTER DELETE OR UPDATE ON airwayfiders
FOR each ROW
DECLARE
  devId INTEGER;
BEGIN
  select t.id INTO devId from devices t where t.linktofider = :old.basic_fider_id;
  delete profdata_scd
   where (deviceid = devId or deviceid = devId) 
     and (is_losses = 1 or typedata in(261,262,263,264)) 
     and source_id != 2;
EXCEPTION
  when others then
     null;--raise_application_error(-20000, 'trg_del_on_airwayfiders ' || SQLERRM); 
END;


SHOW ERRORS 
;

ALTER TABLE "AIRWAYFIDERS" 
 ADD CONSTRAINT "PK_AIRWAYFIDERS_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "AIRWAYFIDERS" 
 ADD CONSTRAINT "UN_BASIC_FIDER_ID" UNIQUE ("BASIC_FIDER_ID") USING INDEX
;

ALTER TABLE "AIRWAYFIDERS" 
 ADD CONSTRAINT "UN_DUBL_FIDER_ID" UNIQUE ("DUBL_FIDER_ID") USING INDEX
;

ALTER TABLE "AIRWAYTYPES" 
 ADD CONSTRAINT "PK_AIRWAYTYPE_ID"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_DEL_ON_ALTFIDERS" 
AFTER UPDATE OR DELETE ON altfiders FOR EACH ROW
DECLARE
  devId INTEGER;
BEGIN
  select t.id INTO devId from devices t where t.linktofider = :old.fider_id;
  delete profdata_scd p
   where p.deviceid = devId
     and (p.ardtimestamp BETWEEN trunc(:old.datetimestart,'mm')
       and add_months(trunc((:old.datetimeend-1/60/60/24),'mm'),1)
       or p.period >= 2592000  )
       and source_id != 2;
EXCEPTION
  when others then
     null;
--raise_application_error(-20000, 'trg_del_on_airwayfiders ' || SQLERRM);
END;


SHOW ERRORS 
;

ALTER TABLE "ALTFIDERS" 
 ADD CONSTRAINT "PK_ALTFIDER_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "ALTFORMULAS" 
 ADD CONSTRAINT "PK_ALTFORMULA_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "AR_CFG_COLORS" 
 ADD CONSTRAINT "PK_AR_CFG_COLORS"
	PRIMARY KEY ("USER_ID","MSG_TYPE_ID") USING INDEX
;

ALTER TABLE "AR_CFG_COLUMNS" 
 ADD CONSTRAINT "PK_AR_CFG_COLUMNS"
	PRIMARY KEY ("USER_ID","COLUMN_ID") USING INDEX
;

ALTER TABLE "AR_COLUMNS" 
 ADD CONSTRAINT "PK_AR_COLUMNS"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE UNIQUE INDEX "IDX_UNIQ_BILDATA"   
 ON "BILDATA" ("DEVICEID","ARDTIMESTAMP","TYPEDATA") 
LOGGING
TABLESPACE	USERS
PCTFREE		10
INITRANS	2
MAXTRANS	255
STORAGE (
	INITIAL		327680
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
NOPARALLEL
;

CREATE OR REPLACE TRIGGER "TRG_BILDATA_SCD_SYNCHR" 
AFTER INSERT OR UPDATE ON bildata
FOR each ROW
BEGIN  
    delete profdata_scd p
     where p.deviceid = :old.deviceid
      and p.ardtimestamp = :old.ardtimestamp
      and p.source_id != 2;
END;


SHOW ERRORS 
;

ALTER TABLE "BILDATA" 
 ADD CONSTRAINT "UK_BILDATA" UNIQUE ("DEVICEID","TYPEDATA","ARDTIMESTAMP") USING INDEX
;

ALTER TABLE "CALC_ENERGY_TYPES" 
 ADD CONSTRAINT "PK_CALC_EN_TYPES_FID"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_CALC_LOG_ID" 
BEFORE INSERT OR UPDATE ON calc_log
FOR each ROW
BEGIN
   IF :NEW.fid IS NULL THEN
     SELECT seq_log_id.NEXTVAL INTO :NEW.fid FROM dual;
   END IF;
END;


SHOW ERRORS 
;

ALTER TABLE "CALCDATA" 
 ADD CONSTRAINT "UK_CALCDATA" UNIQUE ("ARDTIMESTAMP","FORMULA_ID","ROUNDTYPE_ID","PERIOD","IS_COEF") USING INDEX
;

ALTER TABLE "CATEGORIES_PS" 
 ADD CONSTRAINT "PK_CATEGORIES_PS"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "CHANNEL_CUSTOM_TYPES" 
 ADD CONSTRAINT "PK_CHL_CUSTOM_TYPES"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "CHANNELDEVICES" 
 ADD CONSTRAINT "PK_CHANNELDEVICE"
	PRIMARY KEY ("CHL_ID","TYPEDEVICE_ID") USING INDEX
;

ALTER TABLE "CHANNELS" 
 ADD CONSTRAINT "PK_CHANNEL"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "CHANNELS_CUSTOM" 
 ADD CONSTRAINT "UK_CHANNELS_CUSTOM" UNIQUE ("USER_ID","CHL_CUSTOM_TYPE_ID","CHL_ID") USING INDEX
;

ALTER TABLE "CHANNELTYPES" 
 ADD CONSTRAINT "PK_CHANNELTYPE"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_CHANNELVALUES_ID" 
BEFORE INSERT OR UPDATE ON channelvalues
FOR each ROW
BEGIN
   IF :NEW.fid IS NULL THEN
     SELECT seq_channelvalues_id.NEXTVAL INTO :NEW.FID FROM dual;
   END IF;
END;

/* Structure for the `DEVICECHANGE` table :  */


SHOW ERRORS 
;

ALTER TABLE "CHANNELVALUES" 
 ADD CONSTRAINT "PK_CHANNELVALUES_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "CHANNELVALUES" 
 ADD CONSTRAINT "UK_CHANNELVALUE" UNIQUE ("DEVICE_ID","CHL_ID") USING INDEX
;

ALTER TABLE "COMMUNICATIONS" 
 ADD CONSTRAINT "PK_COMMUNICATIONS_FID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "CONNECTION_TYPES" 
 ADD CONSTRAINT "PK_CONNECTION_TYPES"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "DATASNAP_SUBSCRIPTIONS" 
 ADD CONSTRAINT "PK_DS_SUBSCRIPTIONS"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "DEVICECHANGE" 
 ADD CONSTRAINT "PK_DEVCHANGE"
	PRIMARY KEY ("RID") USING INDEX
;

ALTER TABLE "DEVICECHANGECHANNELS" 
 ADD CONSTRAINT "UK_DEVCHANGECHLS" UNIQUE ("DEVCHANGE_ID","DEVCHANGETYPE_ID","CHL_ID") USING INDEX
;

ALTER TABLE "DEVICECHANGETYPES" 
 ADD CONSTRAINT "PK_DEVCHANGETYPES"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "DEVICES" 
 ADD CONSTRAINT "PK_DEVICE"
	PRIMARY KEY ("ID") USING INDEX
;

ALTER TABLE "DST" 
 ADD CONSTRAINT "DSTPK"
	PRIMARY KEY ("YEAR","DSTS","DSTE") USING INDEX
;

ALTER TABLE "ENERGY_PRICE" 
 ADD CONSTRAINT "PK_ENERGY_PRICE"
	PRIMARY KEY ("CHL_ID") USING INDEX
;

ALTER TABLE "FORMFRACS" 
 ADD CONSTRAINT "UK_FORMFRACS" UNIQUE ("ARDTIMESTAMP","FORMULA_ID","PERIOD","TIMEFORMATTYPE","ROUNDTYPE","IS_COEF") USING INDEX
;

ALTER TABLE "FORMGROUPS" 
 ADD CONSTRAINT "PK_FORMGROUP_ID"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_UP_FORMOPERANDS" 
AFTER UPDATE ON formoperands
FOR each ROW
BEGIN
  delete formfracs f
   where f.formula_id = :new.formula_id;
  delete calcdata f
   where f.formula_id = :new.formula_id;
END;


SHOW ERRORS 
;

ALTER TABLE "FORMOPERANDS" 
 ADD CONSTRAINT "PK_FORMOPERAND_ID"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_FORMTASKS_ID" 
BEFORE INSERT OR UPDATE ON formtasks
FOR each ROW
BEGIN
   IF :NEW.fid IS NULL THEN
     SELECT seq_formtasks_id.NEXTVAL INTO :NEW.fid FROM dual;
   END IF;
END;


SHOW ERRORS 
;

ALTER TABLE "FORMTASKS" 
 ADD CONSTRAINT "PK_FORMTASK_ID"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_UP_FORMULAS" 
AFTER UPDATE ON formulas
FOR each ROW
BEGIN
  delete formfracs f
   where f.formula_id = :new.fid; 
  delete calcdata f
   where f.formula_id = :new.fid; 
END;


SHOW ERRORS 
;

ALTER TABLE "FORMULAS" 
 ADD CONSTRAINT "PK_FORMULA_ID"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE INDEX "FK_FRACS_CHANNEL_ID"   
 ON "FRACS" ("CHANNEL_ID") 
LOGGING
TABLESPACE	USERS
PCTFREE		10
INITRANS	2
MAXTRANS	255
STORAGE (
	INITIAL		2097152
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
NOPARALLEL
;

ALTER TABLE "FRACS" 
 ADD CONSTRAINT "UK_FRACS" UNIQUE ("ARDTIMESTAMP","DEVICE_ID","CHANNEL_ID","PERIOD","ROUNDTYPE","IS_COEF","IS_LOSSES") USING INDEX
;

ALTER TABLE "GPRSTERMINALS" 
 ADD CONSTRAINT "GPRSTERMINALS_PK"
	PRIMARY KEY ("ID") USING INDEX
;

ALTER TABLE "GRAPH_GROUPS" 
 ADD CONSTRAINT "PK_GRAPH_GROUPS"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "GRAPH_SERIES" 
 ADD CONSTRAINT "PK_GRAPH_SERIES"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "GRAPH_SERIES_GROUPS" 
 ADD CONSTRAINT "PK_GRAPH_S_GROUPS"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "GRAPH_TRENDS" 
 ADD CONSTRAINT "PK_GRAPH_TRANDS"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "GROUP_GROUPS" 
 ADD CONSTRAINT "PK_GROUPGROUP_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "GROUPS" 
 ADD CONSTRAINT "PK_GROUP"
	PRIMARY KEY ("ID") USING INDEX
;

ALTER TABLE "LIMITS" 
 ADD CONSTRAINT "PK_LIMITS_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MAKET_EXP_CODES" 
 ADD CONSTRAINT "PK_MAK_EXP_CODE_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MAKET_EXP_GROUPS" 
 ADD CONSTRAINT "PK_MAKET_EXP_GROUP_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MAKETCODES" 
 ADD CONSTRAINT "PK_MAKETCODE_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MAKETFORMATTYPES" 
 ADD CONSTRAINT "PK_MAKETFORMATTYPE_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MAKETGROUPS" 
 ADD CONSTRAINT "PK_MAKETGROUP_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MAKETS" 
 ADD CONSTRAINT "PK_MAKET_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MAKETS_EXP" 
 ADD CONSTRAINT "PK_MAKET_EXP_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MAKETSAVEDDATA" 
 ADD CONSTRAINT "MAKSAVDATA_UNIQ_IDX" UNIQUE ("MID","ARDTIMESTAMP","MDATATYPE","VALNOM") USING INDEX
;

ALTER TABLE "MAKETTYPES" 
 ADD CONSTRAINT "PK_MAKETTYPE_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MEASUREMENT_VALUE_SOURCES" 
 ADD CONSTRAINT "PK_MEASUREMENT_VALUE_SOURCE"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_MIGRATION_HIST_ID" 
  before insert on migration_hist  
  for each row
declare
  -- local variables here
begin
   IF :NEW.fid IS NULL THEN
     SELECT seq_migration_hist_id.NEXTVAL INTO :NEW.FID FROM dual;
   END IF;
end TRG_MIGRATION_HIST_ID;


SHOW ERRORS 
;

ALTER TABLE "MIGRATION_HIST" 
 ADD CONSTRAINT "PK_MIGRATION_HIST"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE INDEX "IDX_MOMDATA"   
 ON "MOMDATA" ("DEVICEID") 
LOGGING
TABLESPACE	USERS
PCTFREE		10
INITRANS	2
MAXTRANS	255
STORAGE (
	INITIAL		393216
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
NOPARALLEL
;

CREATE OR REPLACE TRIGGER "TRG_MOMDATA_SCD_SYNCHR" 
AFTER INSERT OR UPDATE ON momdata
FOR each ROW
BEGIN        
    delete profdata_scd p
     where p.deviceid = :old.deviceid
      and p.ardtimestamp = :old.ardtimestamp
      and p.source_id != 2;
END;


SHOW ERRORS 
;

ALTER TABLE "MOMDATA" 
 ADD CONSTRAINT "UK_MOMDATA" UNIQUE ("DEVICEID","TYPEDATA","ARDTIMESTAMP") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_MSG_FILTERGROUPS_ID" 
  before insert on msg_filtergroups  
  for each row
declare
  -- local variables here
begin
  IF :NEW.FID IS NULL THEN
    SELECT seq_msg_filtergroup_id.NEXTVAL INTO :NEW.FID FROM dual;
  END IF;    
end TRG_MSG_FILTERGROUPS_ID;


SHOW ERRORS 
;

ALTER TABLE "MSG_FILTERGROUPS" 
 ADD CONSTRAINT "PK_FILTERGROUP_ID"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_MSG_FILTERS_ID" 
  before insert on msg_filters  
  for each row
declare
  -- local variables here
begin
  IF :NEW.FID IS NULL THEN
    SELECT seq_msg_filter_id.NEXTVAL INTO :NEW.FID FROM dual;
  END IF;  
end TRG_MSG_FILTERS_ID;


SHOW ERRORS 
;

ALTER TABLE "MSG_FILTERS" 
 ADD CONSTRAINT "PK_MSG_FILTER_ID"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_DO_ALARMSREPORTING_REFRESH" 
  after insert on msg_journal
  for each row
begin
  dbms_alert.signal('AR_Refresh', To_Char(:new.fid));
end TRG_DO_ALARMSREPORTING_REFRESH;


SHOW ERRORS 
;

CREATE OR REPLACE TRIGGER "TRG_MSG_JOURNAL_ID" 
  before insert on msg_journal  
  for each row
declare
  -- local variables here
begin
   IF :NEW.fid IS NULL THEN
     SELECT seq_msg_journal_id.NEXTVAL INTO :NEW.FID FROM dual;
   END IF;
end trg_msg_journal_id;


SHOW ERRORS 
;

ALTER TABLE "MSG_JOURNAL" 
 ADD CONSTRAINT "PK_MSG_JOURNAL_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MSG_KVITNOTES" 
 ADD CONSTRAINT "PK_KVITNOTE_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MSG_KVITS" 
 ADD CONSTRAINT "PK_MSG_KVITS_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MSG_SOURCES" 
 ADD CONSTRAINT "PK_MSG_SORCES"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MSG_TEXTVALUES" 
 ADD CONSTRAINT "PK_MSG_TEXTVALUES_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "MSG_TYPES" 
 ADD CONSTRAINT "PK_MSG_TYPE"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "OLDCHANNELS" 
 ADD CONSTRAINT "PK_OLD_CHANNEL"
	PRIMARY KEY ("CHL_ID","OLDCHL_ID") USING INDEX
;

ALTER TABLE "OPERANDTYPES" 
 ADD CONSTRAINT "PK_OPERANDTYPE_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "OTPOSITION" 
 ADD CONSTRAINT "PK_OTPOSITION"
	PRIMARY KEY ("ID") USING INDEX
;

ALTER TABLE "OWNERTYPES" 
 ADD CONSTRAINT "PK_OWNER"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_BI_PERIODDELETE_ID" 
BEFORE INSERT OR UPDATE ON perioddelete
FOR each ROW
BEGIN
   IF :NEW.id IS NULL THEN
     SELECT seq_perioddelete_id.NEXTVAL INTO :NEW.id FROM dual;
   END IF;
END;

-- spr_channel


SHOW ERRORS 
;

ALTER TABLE "PERIODDELETE" 
 ADD CONSTRAINT "FK_PERIOD_DELETE_ID"
	PRIMARY KEY ("ID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_PROFDATA_PERIOD" 
BEFORE INSERT OR UPDATE ON profdata
FOR each ROW
declare
  chltype INTEGER;
BEGIN
  BEGIN
    SELECT ch.chltype_id INTO chltype FROM channels ch
      WHERE ch.fid = :NEW.TYPEDATA;
  EXCEPTION
    when others then
      :NEW.Period := null;  
  END;
  IF chltype = 9 THEN
    IF :NEW.Period IS NULL THEN
      SELECT t.custom_period
        INTO :NEW.Period from devices t
       where t.id = :NEW.deviceid;
    END IF;
  ELSE
    IF :NEW.Period IS NULL THEN
      SELECT t.period
        INTO :NEW.Period from devices t
       where t.id = :NEW.deviceid;
    END IF;
  END IF;
END;


SHOW ERRORS 
;

CREATE OR REPLACE TRIGGER "TRG_PROFDATA_SCD_SYNCHR" 
AFTER INSERT OR UPDATE ON profdata
FOR each ROW
BEGIN
    delete profdata_scd p
     where p.deviceid = :old.deviceid
      and p.ardtimestamp = :old.ardtimestamp
      and p.source_id != 2;
END;


SHOW ERRORS 
;

ALTER TABLE "PROFDATA" 
 ADD CONSTRAINT "UK_PROFDATA" UNIQUE ("DEVICEID","TYPEDATA","ARDTIMESTAMP") USING INDEX
;

CREATE UNIQUE INDEX "UK_PROFDATA_SCD"   
 ON "PROFDATA_SCD" ("DEVICEID","TYPEDATA","ARDTIMESTAMP","PERIOD","ROUND_TYPE_ID","IS_COEF","IS_LOSSES") 
LOGGING
TABLESPACE	USERS
PCTFREE		10
INITRANS	2
MAXTRANS	255
STORAGE (
	INITIAL		28311552
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
		)
NOPARALLEL
;

ALTER TABLE "PROFDATA_SCD" 
 ADD CONSTRAINT "UN_PROFDATA" UNIQUE ("DEVICEID","ARDTIMESTAMP","TYPEDATA","PERIOD","SOURCE_ID","ROUND_TYPE_ID","IS_COEF","IS_LOSSES") USING INDEX
;

ALTER TABLE "PROPERTIES" 
 ADD CONSTRAINT "PK_PROPERTY"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "PROPERTYDEVICES" 
 ADD CONSTRAINT "PK_PROPERTYDEVICES"
	PRIMARY KEY ("DEVICETYPE_ID","PROPERTY_ID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_PROPERTYOWNERS" 
       before insert or delete on propertyowners
       for each row
begin
  if inserting then
    property.putNewPropertyOwners(:new.ownertype_id,:new.property_id);
  else
    property.delPropertyOwners(:old.ownertype_id,:old.property_id);
  end if;
end trg_propertyowners;


SHOW ERRORS 
;

ALTER TABLE "PROPERTYOWNERS" 
 ADD CONSTRAINT "PK_PROPERTYOWNER"
	PRIMARY KEY ("OWNERTYPE_ID","PROPERTY_ID") USING INDEX
;

ALTER TABLE "PROPERTYTYPES" 
 ADD CONSTRAINT "PK_PROPERTYTYPE"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "PROPERTYVALUES" 
 ADD CONSTRAINT "PK_PROPERTYVALUE"
	PRIMARY KEY ("OWNERTYPE_ID","PROPERTY_ID","OWNER_ID") USING INDEX
;

ALTER TABLE "QUALITY_TYPES" 
 ADD CONSTRAINT "PK_QUALITY_TYPE"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "REPORTARGUMENTS" 
 ADD CONSTRAINT "PK_REPORTARGUMENT_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "REPORTARGVALUES" 
 ADD CONSTRAINT "PK_REPORTARGVALUE"
	PRIMARY KEY ("REPORT_ID","ARG_ID") USING INDEX
;

ALTER TABLE "REPORTS" 
 ADD CONSTRAINT "PK_REPORT_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "REPORTTEMPLATES" 
 ADD CONSTRAINT "PK_REPORTTEMPLATE_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "REPORTTREE" 
 ADD CONSTRAINT "PK_REPORTREE_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "ROUNDTYPES" 
 ADD CONSTRAINT "PK_ROUNDTYPE_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "SEASONS" 
 ADD CONSTRAINT "PK_SEASONS_ID"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_SPR_CONNECT_ID" 
BEFORE INSERT OR UPDATE ON spr_connect
FOR each ROW
BEGIN
   IF :NEW.id IS NULL THEN
     SELECT seq_spr_connect_id.NEXTVAL INTO :NEW.id FROM dual;
   END IF;
END;

/* Structure for the `UPPD` table :  */


SHOW ERRORS 
;

CREATE OR REPLACE TRIGGER "TRG_DEL_LIM_CONNECT" 
BEFORE DELETE ON spr_connect
FOR each ROW
BEGIN
  delete limits l
   where l.owner_id = :old.id
   and l.ownertype_id=7;

END;


SHOW ERRORS 
;

ALTER TABLE "SPR_CONNECT" 
 ADD CONSTRAINT "PK_FIDER_ID"
	PRIMARY KEY ("ID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_SPR_PS_ID" 
BEFORE INSERT OR UPDATE ON spr_ps
FOR each ROW
BEGIN
   IF :NEW.id IS NULL THEN
     SELECT seq_spr_ps_id.NEXTVAL INTO :NEW.id FROM dual;
   END IF;
END;


SHOW ERRORS 
;

CREATE OR REPLACE TRIGGER "TRG_DEL_LIM_PS" 
BEFORE DELETE ON spr_ps
FOR each ROW
BEGIN
  delete limits l
   where l.owner_id = :old.id
   and l.ownertype_id=5;

END;


SHOW ERRORS 
;

ALTER TABLE "SPR_PS" 
 ADD CONSTRAINT "PK_SPR_PS_ID"
	PRIMARY KEY ("ID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_SPR_SUB_ID" 
BEFORE INSERT OR UPDATE ON spr_sub
FOR each ROW
BEGIN
   IF :NEW.id IS NULL THEN
     SELECT seq_spr_sub_id.NEXTVAL INTO :NEW.id FROM dual;
   END IF;
END;


SHOW ERRORS 
;

CREATE OR REPLACE TRIGGER "TRG_DEL_LIM_SUB" 
BEFORE DELETE ON spr_sub
FOR each ROW
BEGIN
  delete limits l
   where l.owner_id = :old.id
   and l.ownertype_id=6;

END;


SHOW ERRORS 
;

ALTER TABLE "SPR_SUB" 
 ADD CONSTRAINT "PK_SUB_ID"
	PRIMARY KEY ("ID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_SPR_THREADS_ID" 
BEFORE INSERT OR UPDATE ON spr_threads
FOR each ROW
BEGIN
   IF :NEW.id IS NULL THEN
     SELECT seq_spr_threads_id.NEXTVAL INTO :NEW.id FROM dual;
   END IF;
END;


SHOW ERRORS 
;

ALTER TABLE "SPR_THREADS" 
 ADD CONSTRAINT "PK_SPR_THREADS_ID"
	PRIMARY KEY ("ID") USING INDEX
;

ALTER TABLE "SYS_BUFFER_PARAMS" 
 ADD CONSTRAINT "SYS_C007255"
	PRIMARY KEY ("ID") USING INDEX
;

ALTER TABLE "SYS_BUFFER_RESULTS" 
 ADD CONSTRAINT "SYS_C007258"
	PRIMARY KEY ("ID") USING INDEX
;

ALTER TABLE "SYS_DS_DEVICES" 
 ADD CONSTRAINT "SYS_C007263"
	PRIMARY KEY ("ID_A1") USING INDEX
;

ALTER TABLE "SYS_DS_SERVERS" 
 ADD CONSTRAINT "SYS_C007272"
	PRIMARY KEY ("ID") USING INDEX
;

ALTER TABLE "SYS_SEMAFOR" 
 ADD CONSTRAINT "SYS_C007274"
	PRIMARY KEY ("ID") USING INDEX
;

ALTER TABLE "TARIFS" 
 ADD CONSTRAINT "PK_TARIFS_ID"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_THREADS_ID" 
BEFORE INSERT OR UPDATE ON threads
FOR each ROW
BEGIN
   IF :NEW.id IS NULL THEN
     SELECT seq_threads_id.NEXTVAL INTO :NEW.id FROM dual;
   END IF;
END;


SHOW ERRORS 
;

ALTER TABLE "THREADS" 
 ADD CONSTRAINT "PK_THREAD_ID"
	PRIMARY KEY ("ID") USING INDEX
;

ALTER TABLE "TIMEFORMATTYPES" 
 ADD CONSTRAINT "PK_TIMEFORMATTYPES_TFT"
	PRIMARY KEY ("TIMEFORMATTYPE") USING INDEX
;

ALTER TABLE "TRANSFIDERS_2W" 
 ADD CONSTRAINT "PK_TRANS2WFIDERS_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "TRANSFIDERS_3W" 
 ADD CONSTRAINT "PK_TRANS3WFIDERS_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "TRANSTYPES_2W" 
 ADD CONSTRAINT "PK_TRANSTYPE_2W_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "TRANSTYPES_3W" 
 ADD CONSTRAINT "PK_TRANSTYPE_3W_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "TYPEDEVICE" 
 ADD CONSTRAINT "PK_TYPEDEVICE_ID"
	PRIMARY KEY ("ID") USING INDEX
;

ALTER TABLE "UNITS" 
 ADD CONSTRAINT "PK_UNIT"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_USER_FIDERS_ID" 
  before insert on user_fiders
  for each row
declare
  -- local variables here
begin
   IF :NEW.fid IS NULL THEN
     SELECT SEQ_USER_FIDERS_ID.NEXTVAL INTO :NEW.FID FROM dual;
   END IF;
end TRG_USER_FIDERS_ID;


SHOW ERRORS 
;

ALTER TABLE "USER_FIDERS" 
 ADD CONSTRAINT "PK_USER_FID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "USER_FORMULAS" 
 ADD CONSTRAINT "PK_USER_FORMID"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_USER_IN_GROUPS_ID" 
  before insert on user_in_groups  
  for each row
declare
  -- local variables here
begin
   IF :NEW.fid IS NULL THEN
     SELECT SEQ_USER_IN_GROUPS_ID.NEXTVAL INTO :NEW.FID FROM dual;
   END IF;  
end TRG_USER_IN_GROUPS_ID;


SHOW ERRORS 
;

ALTER TABLE "USER_IN_GROUPS" 
 ADD CONSTRAINT "PK_U_IN_G"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_USER_REPORTS_ID" 
  before insert on user_reports
  for each row
declare
  -- local variables here
begin
   IF :NEW.fid IS NULL THEN
     SELECT SEQ_USER_REPORTS_ID.NEXTVAL INTO :NEW.FID FROM dual;
   END IF;
end TRG_USER_REPORTS_ID;


SHOW ERRORS 
;

ALTER TABLE "USER_REPORTS" 
 ADD CONSTRAINT "PK_USER_REP"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "USER_RIGHTS" 
 ADD CONSTRAINT "PK_USER_RIGHTS"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "USER_STATE_OF_LIST" 
 ADD CONSTRAINT "PK_STATE_OF_LIST"
	PRIMARY KEY ("FID") USING INDEX
;

CREATE OR REPLACE TRIGGER "TRG_USER_TASK_RIGHTS_ID" 
  before insert on user_TASK_RIGHTS
  for each row
declare
  -- local variables here
begin
   IF :NEW.fid IS NULL THEN
     SELECT SEQ_USER_TASK_RIGHTS_ID.NEXTVAL INTO :NEW.FID FROM dual;
   END IF;
end TRG_USER_TASK_RIGHTS_ID;


SHOW ERRORS 
;

ALTER TABLE "USER_TASK_RIGHTS" 
 ADD CONSTRAINT "PK_U_T_R"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "USER_TASKS" 
 ADD CONSTRAINT "PK_USER_TASKS"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "USERGROUPS" 
 ADD CONSTRAINT "PK_USERGROUP_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "USERS" 
 ADD CONSTRAINT "PK_USER_ID"
	PRIMARY KEY ("FID") USING INDEX
;

ALTER TABLE "VIRTUALTYPEDEVICE" 
 ADD CONSTRAINT "PK_VIRT_TYPEDEVICE_ID"
	PRIMARY KEY ("ID") USING INDEX
;

ALTER TABLE "AIRWAYFIDERS" 
 ADD CONSTRAINT "FK_AIRWAYFIDERS_AIRWAY_ID"
	FOREIGN KEY ("AIRWAY_ID") REFERENCES "AIRWAYTYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "AIRWAYFIDERS" 
 ADD CONSTRAINT "FK_AIRWAYFIDERS_BASIC_FIDER_ID"
	FOREIGN KEY ("BASIC_FIDER_ID") REFERENCES "SPR_CONNECT" ("ID") ON DELETE Set Null
;

ALTER TABLE "AIRWAYFIDERS" 
 ADD CONSTRAINT "FK_AIRWAYFIDERS_DUBL_FIDER_ID"
	FOREIGN KEY ("DUBL_FIDER_ID") REFERENCES "SPR_CONNECT" ("ID") ON DELETE Set Null
;

ALTER TABLE "ALTFIDERS" 
 ADD CONSTRAINT "FK_ALTFIDERS_ALTFIDER_ID"
	FOREIGN KEY ("ALTFIDER_ID") REFERENCES "SPR_CONNECT" ("ID") ON DELETE Set Null
;

ALTER TABLE "ALTFIDERS" 
 ADD CONSTRAINT "FK_ALTFIDERS_FIDER_ID"
	FOREIGN KEY ("FIDER_ID") REFERENCES "SPR_CONNECT" ("ID") ON DELETE Cascade
;

ALTER TABLE "ALTFORMULAS" 
 ADD CONSTRAINT "FK_ALTFORMULAS_ALTFORMULA_ID"
	FOREIGN KEY ("ALTFORMULA_ID") REFERENCES "FORMULAS" ("FID") ON DELETE Set Null
;

ALTER TABLE "ALTFORMULAS" 
 ADD CONSTRAINT "FK_ALTFORMULAS_FORMULA_ID"
	FOREIGN KEY ("FORMULA_ID") REFERENCES "FORMULAS" ("FID") ON DELETE Cascade
;

ALTER TABLE "AR_CFG_COLORS" 
 ADD CONSTRAINT "FK_AR_CFG_COLORS_MSG_TYPE_ID"
	FOREIGN KEY ("MSG_TYPE_ID") REFERENCES "MSG_TYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "AR_CFG_COLORS" 
 ADD CONSTRAINT "FK_AR_CFG_COLORS_USER_ID"
	FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("FID") ON DELETE Cascade
;

ALTER TABLE "AR_CFG_COLUMNS" 
 ADD CONSTRAINT "FK_AR_CFG_COLUMNS_COLUMN_ID"
	FOREIGN KEY ("COLUMN_ID") REFERENCES "AR_COLUMNS" ("FID") ON DELETE Cascade
;

ALTER TABLE "AR_CFG_COLUMNS" 
 ADD CONSTRAINT "FK_AR_CFG_COLUMNS_USER_ID"
	FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("FID") ON DELETE Cascade
;

ALTER TABLE "BILDATA" 
 ADD CONSTRAINT "FK_BILDATA_CHANNEL_ID"
	FOREIGN KEY ("TYPEDATA") REFERENCES "CHANNELS" ("FID") ON DELETE Cascade
;

ALTER TABLE "BILDATA" 
 ADD CONSTRAINT "FK_BILDATA_DEVICE_ID"
	FOREIGN KEY ("DEVICEID") REFERENCES "DEVICES" ("ID") ON DELETE Cascade
;

ALTER TABLE "BILDATA" 
 ADD CONSTRAINT "FK_BILDATA_TFT"
	FOREIGN KEY ("TIMEFORMATTYPE") REFERENCES "TIMEFORMATTYPES" ("TIMEFORMATTYPE") ON DELETE Cascade
;

ALTER TABLE "CALCDATA" 
 ADD CONSTRAINT "FK_CALCDATA_FORMULA_ID"
	FOREIGN KEY ("FORMULA_ID") REFERENCES "FORMULAS" ("FID") ON DELETE Cascade
;

ALTER TABLE "CALCDATA" 
 ADD CONSTRAINT "FK_CALCDATA_QUALITY_ID"
	FOREIGN KEY ("QUALITY_ID") REFERENCES "QUALITY_TYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "CALCDATA" 
 ADD CONSTRAINT "FK_CALCDATA_ROUNDTYPE_ID"
	FOREIGN KEY ("ROUNDTYPE_ID") REFERENCES "ROUNDTYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "CALCDATA" 
 ADD CONSTRAINT "FK_CALCDATA_SOURCE_ID"
	FOREIGN KEY ("SOURCE_ID") REFERENCES "MEASUREMENT_VALUE_SOURCES" ("FID") ON DELETE Cascade
;

ALTER TABLE "CHANNEL_CUSTOM_TYPES" 
 ADD CONSTRAINT "FK_CHL_CUST_CHLTYPE_ID"
	FOREIGN KEY ("CHLTYPE_ID") REFERENCES "CHANNELTYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "CHANNELS" 
 ADD CONSTRAINT "FK_CHANNELS_UNIT_ID"
	FOREIGN KEY ("UNIT_ID") REFERENCES "UNITS" ("FID")
;

ALTER TABLE "CHANNELS" 
 ADD CONSTRAINT "FK_CHLTYPE_ID"
	FOREIGN KEY ("CHLTYPE_ID") REFERENCES "CHANNELTYPES" ("FID")
;

ALTER TABLE "CHANNELS_COREL" 
 ADD CONSTRAINT "FK_CHL_ID_DIR"
	FOREIGN KEY ("CHL_ID_DIRECT") REFERENCES "CHANNELS" ("FID")
;

ALTER TABLE "CHANNELS_COREL" 
 ADD CONSTRAINT "FK_CHL_ID_REV"
	FOREIGN KEY ("CHL_ID_REVERSE") REFERENCES "CHANNELS" ("FID")
;

ALTER TABLE "CHANNELS_CUSTOM" 
 ADD CONSTRAINT "FK_CHLS_CUSTOM_CHL_ID"
	FOREIGN KEY ("CHL_ID") REFERENCES "CHANNELS" ("FID") ON DELETE Cascade
;

ALTER TABLE "CHANNELS_CUSTOM" 
 ADD CONSTRAINT "FK_CHLS_CUSTOM_TYPE_ID"
	FOREIGN KEY ("CHL_CUSTOM_TYPE_ID") REFERENCES "CHANNEL_CUSTOM_TYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "CHANNELS_CUSTOM" 
 ADD CONSTRAINT "FK_CHLS_CUSTOM_USER_ID"
	FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("FID") ON DELETE Cascade
;

ALTER TABLE "CHANNELVALUES" 
 ADD CONSTRAINT "FK_CHANNELVALUES_TFT"
	FOREIGN KEY ("TIMEFORMATTYPE") REFERENCES "TIMEFORMATTYPES" ("TIMEFORMATTYPE") ON DELETE Cascade
;

ALTER TABLE "COMMUNICATIONS" 
 ADD CONSTRAINT "FK_COMMUNIC_CONNECTTYPE"
	FOREIGN KEY ("CONNECTTYPE") REFERENCES "CONNECTION_TYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "COMMUNICATIONS" 
 ADD CONSTRAINT "FK_COMMUNIC_GROUP_ID"
	FOREIGN KEY ("GROUP_ID") REFERENCES "GROUPS" ("ID") ON DELETE Cascade
;

ALTER TABLE "DATASNAP_SUBSCRIPTIONS" 
 ADD CONSTRAINT "FK_DS_SUBSCRIPTIONS_DEVICE_ID"
	FOREIGN KEY ("DEVICE_ID") REFERENCES "DEVICES" ("ID") ON DELETE Cascade
;

ALTER TABLE "DATASNAP_SUBSCRIPTIONS" 
 ADD CONSTRAINT "FK_DS_SUBSCRIPTIONS_USER_ID"
	FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("FID") ON DELETE Cascade
;

ALTER TABLE "DEVICECHANGE" 
 ADD CONSTRAINT "FK_DEVCHANGE_DEV_ID"
	FOREIGN KEY ("DEVICE_ID") REFERENCES "DEVICES" ("ID") ON DELETE Cascade
;

ALTER TABLE "DEVICECHANGE" 
 ADD CONSTRAINT "FK_DEVCHANGE_REM_TYPEDEV_ID"
	FOREIGN KEY ("REM_TYPEDEVICE_ID") REFERENCES "TYPEDEVICE" ("ID") ON DELETE Cascade
;

ALTER TABLE "DEVICECHANGE" 
 ADD CONSTRAINT "FK_DEVCHANGE_SET_TYPEDEV_ID"
	FOREIGN KEY ("SET_TYPEDEVICE_ID") REFERENCES "TYPEDEVICE" ("ID") ON DELETE Cascade
;

ALTER TABLE "DEVICECHANGECHANNELS" 
 ADD CONSTRAINT "FK_DEVCHANGECHLS_CHL_ID"
	FOREIGN KEY ("CHL_ID") REFERENCES "CHANNELS" ("FID") ON DELETE Cascade
;

ALTER TABLE "DEVICECHANGECHANNELS" 
 ADD CONSTRAINT "FK_DEVCHANGECHLS_DEVCHANGE_ID"
	FOREIGN KEY ("DEVCHANGE_ID") REFERENCES "DEVICECHANGE" ("RID") ON DELETE Cascade
;

ALTER TABLE "DEVICECHANGECHANNELS" 
 ADD CONSTRAINT "FK_DEVCHANGECHLS_TYPE_ID"
	FOREIGN KEY ("DEVCHANGETYPE_ID") REFERENCES "DEVICECHANGETYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "DEVICES" 
 ADD CONSTRAINT "FK_DEVICES_GROUP_CET"
	FOREIGN KEY ("CALC_ENERGY_TYPE") REFERENCES "CALC_ENERGY_TYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "DEVICES" 
 ADD CONSTRAINT "FK_DEVICES_GROUP_ID"
	FOREIGN KEY ("GROUPID") REFERENCES "GROUPS" ("ID") ON DELETE Cascade
;

ALTER TABLE "ENERGY_PRICE" 
 ADD CONSTRAINT "FK_ENERGY_PRICE_CHL_ID"
	FOREIGN KEY ("CHL_ID") REFERENCES "CHANNELS" ("FID") ON DELETE Cascade
;

ALTER TABLE "FORMFRACS" 
 ADD CONSTRAINT "FK_FRACS_FORMULA_ID"
	FOREIGN KEY ("FORMULA_ID") REFERENCES "FORMULAS" ("FID") ON DELETE Cascade
;

ALTER TABLE "FORMFRACS" 
 ADD CONSTRAINT "FK_FRACS_TFT_F"
	FOREIGN KEY ("TIMEFORMATTYPE") REFERENCES "TIMEFORMATTYPES" ("TIMEFORMATTYPE") ON DELETE Cascade
;

ALTER TABLE "FORMOPERANDS" 
 ADD CONSTRAINT "FK_FORMOP_FORMULA_ID"
	FOREIGN KEY ("FORMULA_ID") REFERENCES "FORMULAS" ("FID") ON DELETE Cascade
;

ALTER TABLE "FORMTASKS" 
 ADD CONSTRAINT "FK_FORMTASK_FORMULA_ID"
	FOREIGN KEY ("FORMULA_ID") REFERENCES "FORMULAS" ("FID") ON DELETE Cascade
;

ALTER TABLE "FORMULAS" 
 ADD CONSTRAINT "FK_FORMULAS_GROUP_ID"
	FOREIGN KEY ("GROUP_ID") REFERENCES "FORMGROUPS" ("FID") ON DELETE Cascade
;

ALTER TABLE "FORMULAS" 
 ADD CONSTRAINT "FK_FORMULAS_RUONDTYPE_ID"
	FOREIGN KEY ("ROUNDTYPE_ID") REFERENCES "ROUNDTYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "FORMULAS" 
 ADD CONSTRAINT "FK_FORMULAS_TFT"
	FOREIGN KEY ("TIMEFORMATTYPE") REFERENCES "TIMEFORMATTYPES" ("TIMEFORMATTYPE") ON DELETE Cascade
;

ALTER TABLE "FORMULAS" 
 ADD CONSTRAINT "FK_FORMULAS_UNIT_ID"
	FOREIGN KEY ("UNIT_ID") REFERENCES "UNITS" ("FID")
;

ALTER TABLE "FRACS" 
 ADD CONSTRAINT "FK_FRACS_CHANNEL_ID"
	FOREIGN KEY ("CHANNEL_ID") REFERENCES "CHANNELS" ("FID") ON DELETE Cascade
;

ALTER TABLE "GRAPH_GROUPS" 
 ADD CONSTRAINT "FK_GRAPH_GROUPS_USERS_FID"
	FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("FID") ON DELETE Cascade
;

ALTER TABLE "GRAPH_SERIES" 
 ADD CONSTRAINT "FK_GRAPH_SERIES_GROUP_ID"
	FOREIGN KEY ("GROUP_ID") REFERENCES "GRAPH_SERIES_GROUPS" ("FID") ON DELETE Cascade
;

ALTER TABLE "GRAPH_SERIES_GROUPS" 
 ADD CONSTRAINT "FK_GRAPH_S_GROUPS_TREND_ID"
	FOREIGN KEY ("TREND_ID") REFERENCES "GRAPH_TRENDS" ("FID") ON DELETE Cascade
;

ALTER TABLE "GRAPH_TRENDS" 
 ADD CONSTRAINT "FK_GRAPH_TRANDS_GROUP_ID"
	FOREIGN KEY ("GROUP_ID") REFERENCES "GRAPH_GROUPS" ("FID") ON DELETE Cascade
;

ALTER TABLE "GROUPS" 
 ADD CONSTRAINT "FK_GROUP"
	FOREIGN KEY ("GROUP_ID") REFERENCES "GROUP_GROUPS" ("FID") ON DELETE Cascade
;

ALTER TABLE "LIMITS" 
 ADD CONSTRAINT "FK_LIMITS_CHL_ID"
	FOREIGN KEY ("CHL_ID") REFERENCES "CHANNELS" ("FID") ON DELETE Cascade
;

ALTER TABLE "LIMITS" 
 ADD CONSTRAINT "FK_LIMITS_OWNER_ID"
	FOREIGN KEY ("OWNERTYPE_ID") REFERENCES "OWNERTYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "LIMITS" 
 ADD CONSTRAINT "FK_LIMITS_TARIF_ID"
	FOREIGN KEY ("TARIF_ID") REFERENCES "TARIFS" ("FID") ON DELETE Set Null
;

ALTER TABLE "MAKET_EXP_CODES" 
 ADD CONSTRAINT "FK_MAK_EXP_CODES_MAKET_ID"
	FOREIGN KEY ("MAKET_ID") REFERENCES "MAKETS_EXP" ("FID") ON DELETE Cascade
;

ALTER TABLE "MAKET_EXP_CODES" 
 ADD CONSTRAINT "FK_MAK_EXP_CODES_ROUNDTYPE_ID"
	FOREIGN KEY ("ROUNDTYPE_ID") REFERENCES "ROUNDTYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "MAKETCODES" 
 ADD CONSTRAINT "FK_MAKETCODES_MAKET_ID"
	FOREIGN KEY ("MAKET_ID") REFERENCES "MAKETS" ("FID") ON DELETE Cascade
;

ALTER TABLE "MAKETCODES" 
 ADD CONSTRAINT "FK_MAKETCODES_ROUNDTYPE_ID"
	FOREIGN KEY ("ROUNDTYPE_ID") REFERENCES "ROUNDTYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "MAKETS" 
 ADD CONSTRAINT "FK_MAKETS_FORMATTYPE_ID"
	FOREIGN KEY ("FORMATTYPE") REFERENCES "MAKETFORMATTYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "MAKETS" 
 ADD CONSTRAINT "FK_MAKETS_GROUP_ID"
	FOREIGN KEY ("GROUP_ID") REFERENCES "MAKETGROUPS" ("FID") ON DELETE Cascade
;

ALTER TABLE "MAKETS" 
 ADD CONSTRAINT "FK_MAKETS_MAKETTYPE_ID"
	FOREIGN KEY ("MAKETTYPE") REFERENCES "MAKETTYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "MAKETS_EXP" 
 ADD CONSTRAINT "FK_MAKETS_EXP_FORMATTYPE_ID"
	FOREIGN KEY ("FORMATTYPE") REFERENCES "MAKETFORMATTYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "MAKETS_EXP" 
 ADD CONSTRAINT "FK_MAKETS_EXP_GROUP_ID"
	FOREIGN KEY ("GROUP_ID") REFERENCES "MAKET_EXP_GROUPS" ("FID") ON DELETE Cascade
;

ALTER TABLE "MOMDATA" 
 ADD CONSTRAINT "FK_MOMDATA_CHANNEL_ID"
	FOREIGN KEY ("TYPEDATA") REFERENCES "CHANNELS" ("FID") ON DELETE Cascade
;

ALTER TABLE "MOMDATA" 
 ADD CONSTRAINT "FK_MOMDATA_DEVICE_ID"
	FOREIGN KEY ("DEVICEID") REFERENCES "DEVICES" ("ID") ON DELETE Cascade
;

ALTER TABLE "MOMDATA" 
 ADD CONSTRAINT "FK_MOMDATA_TFT"
	FOREIGN KEY ("TIMEFORMATTYPE") REFERENCES "TIMEFORMATTYPES" ("TIMEFORMATTYPE") ON DELETE Cascade
;

ALTER TABLE "MSG_FILTERGROUPS" 
 ADD CONSTRAINT "FK_MSG_FILTERGROUPS_USER_ID"
	FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("FID") ON DELETE Cascade
;

ALTER TABLE "MSG_FILTERS" 
 ADD CONSTRAINT "FK_MSG_FILTERS_CATEGORY_PS_ID"
	FOREIGN KEY ("CATEGORY_PS_ID") REFERENCES "CATEGORIES_PS" ("FID") ON DELETE Cascade
;

ALTER TABLE "MSG_FILTERS" 
 ADD CONSTRAINT "FK_MSG_FILTERS_GROUP_ID"
	FOREIGN KEY ("GROUP_ID") REFERENCES "MSG_FILTERGROUPS" ("FID") ON DELETE Cascade
;

ALTER TABLE "MSG_FILTERS" 
 ADD CONSTRAINT "FK_MSG_FILTERS_MSG_TEXT_ID"
	FOREIGN KEY ("MSG_TEXT_ID") REFERENCES "MSG_TEXTVALUES" ("FID") ON DELETE Cascade
;

ALTER TABLE "MSG_FILTERS" 
 ADD CONSTRAINT "FK_MSG_FILTERS_MSG_TYPE_ID"
	FOREIGN KEY ("MSG_TYPE_ID") REFERENCES "MSG_TYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "MSG_FILTERS" 
 ADD CONSTRAINT "FK_MSG_FILTERS_USER_ID"
	FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("FID") ON DELETE Cascade
;

ALTER TABLE "MSG_JOURNAL" 
 ADD CONSTRAINT "FK_JOURNAL_CHL_ID"
	FOREIGN KEY ("CHL_ID") REFERENCES "CHANNELS" ("FID") ON DELETE Cascade
;

ALTER TABLE "MSG_JOURNAL" 
 ADD CONSTRAINT "FK_JOURNAL_MSG_TEXT_ID"
	FOREIGN KEY ("MSG_TEXT_ID") REFERENCES "MSG_TEXTVALUES" ("FID") ON DELETE Cascade
;

ALTER TABLE "MSG_JOURNAL" 
 ADD CONSTRAINT "FK_JOURNAL_MSG_TYPE_ID"
	FOREIGN KEY ("MSG_TYPE_ID") REFERENCES "MSG_TYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "MSG_JOURNAL" 
 ADD CONSTRAINT "FK_JOURNAL_SOURCE_ID"
	FOREIGN KEY ("SOURCE_ID") REFERENCES "MSG_SOURCES" ("FID") ON DELETE Cascade
;

ALTER TABLE "MSG_JOURNAL" 
 ADD CONSTRAINT "FK_JOURNAL_USER_ID"
	FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("FID") ON DELETE Cascade
;

ALTER TABLE "MSG_KVITS" 
 ADD CONSTRAINT "FK_MSG_KVITS_JOURNAL_ID"
	FOREIGN KEY ("JOURNAL_ID") REFERENCES "MSG_JOURNAL" ("FID") ON DELETE Cascade
;

ALTER TABLE "MSG_KVITS" 
 ADD CONSTRAINT "FK_MSG_KVITS_KVITNOTE_ID"
	FOREIGN KEY ("KVITNOTE_ID") REFERENCES "MSG_KVITNOTES" ("FID")
;

ALTER TABLE "MSG_KVITS" 
 ADD CONSTRAINT "FK_MSG_KVITS_USER_ID"
	FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("FID") ON DELETE Cascade
;

ALTER TABLE "OLDCHANNELS" 
 ADD CONSTRAINT "FK_CHL_ID"
	FOREIGN KEY ("CHL_ID") REFERENCES "CHANNELS" ("FID") ON DELETE Cascade
;

ALTER TABLE "PROFDATA" 
 ADD CONSTRAINT "FK_PORFDATA_CHANNEL_ID"
	FOREIGN KEY ("TYPEDATA") REFERENCES "CHANNELS" ("FID") ON DELETE Cascade
;

ALTER TABLE "PROFDATA" 
 ADD CONSTRAINT "FK_PORFDATA_DEVICE_ID"
	FOREIGN KEY ("DEVICEID") REFERENCES "DEVICES" ("ID") ON DELETE Cascade
;

ALTER TABLE "PROFDATA" 
 ADD CONSTRAINT "FK_PROFDATA_TFT"
	FOREIGN KEY ("TIMEFORMATTYPE") REFERENCES "TIMEFORMATTYPES" ("TIMEFORMATTYPE") ON DELETE Cascade
;

ALTER TABLE "PROFDATA_SCD" 
 ADD CONSTRAINT "FK_PROFDATA_SCD_CHANNEL_ID"
	FOREIGN KEY ("TYPEDATA") REFERENCES "CHANNELS" ("FID") ON DELETE Cascade
;

ALTER TABLE "PROFDATA_SCD" 
 ADD CONSTRAINT "FK_PROFDATA_SCD_DEVICE_ID"
	FOREIGN KEY ("DEVICEID") REFERENCES "DEVICES" ("ID") ON DELETE Cascade
;

ALTER TABLE "PROFDATA_SCD" 
 ADD CONSTRAINT "FK_PROFDATA_SCD_QUALITY_ID"
	FOREIGN KEY ("QUALITY_ID") REFERENCES "QUALITY_TYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "PROFDATA_SCD" 
 ADD CONSTRAINT "FK_PROFDATA_SCD_ROUND_ID"
	FOREIGN KEY ("ROUND_TYPE_ID") REFERENCES "ROUNDTYPES" ("FID") ON DELETE Cascade
;

ALTER TABLE "PROFDATA_SCD" 
 ADD CONSTRAINT "FK_PROFDATA_SCD_SOURCE_ID"
	FOREIGN KEY ("SOURCE_ID") REFERENCES "MEASUREMENT_VALUE_SOURCES" ("FID") ON DELETE Cascade
;

ALTER TABLE "PROPERTYDEVICES" 
 ADD CONSTRAINT "FK_PROPERTY_ID"
	FOREIGN KEY ("PROPERTY_ID") REFERENCES "PROPERTIES" ("FID") ON DELETE Cascade
;

ALTER TABLE "PROPERTYOWNERS" 
 ADD CONSTRAINT "FK_PO_PROPERTY_ID"
	FOREIGN KEY ("PROPERTY_ID") REFERENCES "PROPERTIES" ("FID")
;

ALTER TABLE "PROPERTYVALUES" 
 ADD CONSTRAINT "FK_PV_OWNERTYPE_ID"
	FOREIGN KEY ("OWNERTYPE_ID") REFERENCES "OWNERTYPES" ("FID")
;

ALTER TABLE "PROPERTYVALUES" 
 ADD CONSTRAINT "FK_PV_PROPERTY_ID"
	FOREIGN KEY ("PROPERTY_ID") REFERENCES "PROPERTIES" ("FID")
;

ALTER TABLE "REPORTARGUMENTS" 
 ADD CONSTRAINT "FK_REPORTARGS_TPL_ID"
	FOREIGN KEY ("TEMPLATE_ID") REFERENCES "REPORTTEMPLATES" ("FID") ON DELETE Cascade
;

ALTER TABLE "REPORTS" 
 ADD CONSTRAINT "FK_REPORTS_TPL_ID"
	FOREIGN KEY ("TEMPLATE_ID") REFERENCES "REPORTTEMPLATES" ("FID") ON DELETE Cascade
;

ALTER TABLE "REPORTTREE" 
 ADD CONSTRAINT "FK_REPORTS_REPORT_ID"
	FOREIGN KEY ("REPORT_ID") REFERENCES "REPORTS" ("FID") ON DELETE Cascade
;

ALTER TABLE "SPR_PS" 
 ADD CONSTRAINT "FK_CATEGORY_PS_ID"
	FOREIGN KEY ("CATEGORY_PS_ID") REFERENCES "CATEGORIES_PS" ("FID") ON DELETE Cascade
;

ALTER TABLE "SPR_THREADS" 
 ADD CONSTRAINT "FK_SPR_THREADS_GROUP_ID"
	FOREIGN KEY ("GROUPID") REFERENCES "GROUPS" ("ID") ON DELETE Cascade
;

ALTER TABLE "SPR_THREADS" 
 ADD CONSTRAINT "FK_SPR_THREADS_TREAD_ID"
	FOREIGN KEY ("THREADID") REFERENCES "THREADS" ("ID") ON DELETE Cascade
;

ALTER TABLE "TARIFS" 
 ADD CONSTRAINT "FK_TARIFS_SEASON_ID"
	FOREIGN KEY ("SEASON_ID") REFERENCES "SEASONS" ("FID") ON DELETE Cascade
;

ALTER TABLE "TRANSFIDERS_2W" 
 ADD CONSTRAINT "FK_TRANS2WFIDERS_FIDER_ID"
	FOREIGN KEY ("FIDER_ID") REFERENCES "SPR_CONNECT" ("ID") ON DELETE Cascade
;

ALTER TABLE "TRANSFIDERS_2W" 
 ADD CONSTRAINT "FK_TRANS2WFIDERS_TYPE_ID"
	FOREIGN KEY ("TRANSTYPE_ID") REFERENCES "TRANSTYPES_2W" ("FID") ON DELETE Cascade
;

ALTER TABLE "TRANSFIDERS_3W" 
 ADD CONSTRAINT "FK_TRANS3WFIDERS_FIDER_ID"
	FOREIGN KEY ("FIDER_ID") REFERENCES "SPR_CONNECT" ("ID") ON DELETE Cascade
;

ALTER TABLE "TRANSFIDERS_3W" 
 ADD CONSTRAINT "FK_TRANS3WFIDERS_TYPE_ID"
	FOREIGN KEY ("TRANSTYPE_ID") REFERENCES "TRANSTYPES_3W" ("FID") ON DELETE Cascade
;

ALTER TABLE "USER_FIDERS" 
 ADD CONSTRAINT "FK_USER_FID_FIDER_ID"
	FOREIGN KEY ("FIDER_ID") REFERENCES "SPR_CONNECT" ("ID") ON DELETE Cascade
;

ALTER TABLE "USER_FIDERS" 
 ADD CONSTRAINT "FK_USER_FID_GROUP_ID"
	FOREIGN KEY ("GROUP_ID") REFERENCES "USERGROUPS" ("FID") ON DELETE Cascade
;

ALTER TABLE "USER_FORMULAS" 
 ADD CONSTRAINT "FK_USER_FORMID_FORMULA_ID"
	FOREIGN KEY ("FORMULA_ID") REFERENCES "FORMULAS" ("FID") ON DELETE Cascade
;

ALTER TABLE "USER_FORMULAS" 
 ADD CONSTRAINT "FK_USER_FORMID_GROUP_ID"
	FOREIGN KEY ("GROUP_ID") REFERENCES "USERGROUPS" ("FID") ON DELETE Cascade
;

ALTER TABLE "USER_IN_GROUPS" 
 ADD CONSTRAINT "FK_U_IN_G_GROUP_ID"
	FOREIGN KEY ("GROUP_ID") REFERENCES "USERGROUPS" ("FID") ON DELETE Cascade
;

ALTER TABLE "USER_IN_GROUPS" 
 ADD CONSTRAINT "FK_U_IN_G_USER_ID"
	FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("FID") ON DELETE Cascade
;

ALTER TABLE "USER_REPORTS" 
 ADD CONSTRAINT "FK_USER_REP_GROUP_ID"
	FOREIGN KEY ("GROUP_ID") REFERENCES "USERGROUPS" ("FID") ON DELETE Cascade
;

ALTER TABLE "USER_REPORTS" 
 ADD CONSTRAINT "FK_USER_REP_REPORT_ID"
	FOREIGN KEY ("REPORT_ID") REFERENCES "REPORTS" ("FID") ON DELETE Cascade
;

ALTER TABLE "USER_TASK_RIGHTS" 
 ADD CONSTRAINT "FK_U_T_R_GROUP_ID"
	FOREIGN KEY ("GROUP_ID") REFERENCES "USERGROUPS" ("FID") ON DELETE Cascade
;

ALTER TABLE "USER_TASK_RIGHTS" 
 ADD CONSTRAINT "FK_U_T_R_TASK_ID"
	FOREIGN KEY ("TASK_ID") REFERENCES "USER_TASKS" ("FID") ON DELETE Cascade
;

ALTER TABLE "USERGROUPS" 
 ADD CONSTRAINT "FK_USERGROUP_FORM_STATE_ID"
	FOREIGN KEY ("FORMULA_STATE_ID") REFERENCES "USER_STATE_OF_LIST" ("FID") ON DELETE Cascade
;

ALTER TABLE "USERGROUPS" 
 ADD CONSTRAINT "FK_USERGROUP_F_STATE_ID"
	FOREIGN KEY ("FIDER_STATE_ID") REFERENCES "USER_STATE_OF_LIST" ("FID") ON DELETE Cascade
;

ALTER TABLE "USERGROUPS" 
 ADD CONSTRAINT "FK_USERGROUP_R_STATE_ID"
	FOREIGN KEY ("REPORT_STATE_ID") REFERENCES "USER_STATE_OF_LIST" ("FID") ON DELETE Cascade
;

ALTER TABLE "USERS" 
 ADD CONSTRAINT "FK_USERS_GROUP_ID"
	FOREIGN KEY ("GROUP_ID") REFERENCES "USERGROUPS" ("FID") ON DELETE Cascade
;
